import { createRenderEffect } from "solid-js";
import sanitizeHtml from "sanitize-html";

const MARKDOWN_TAGS = [
  "a",
  "b",
  "blockquote",
  "br",
  "code",
  "del",
  "div",
  "em",
  "h1",
  "h2",
  "h3",
  "h4",
  "h5",
  "h6",
  "hr",
  "i",
  "img",
  "input",
  "ins",
  "kbd",
  "li",
  "mark",
  "ol",
  "p",
  "pre",
  "s",
  "span",
  "strong",
  "sub",
  "sup",
  "table",
  "tbody",
  "td",
  "th",
  "thead",
  "tr",
  "u",
  "ul",
] as const;
const MARKDOWN_ATTRIBUTES: Record<string, string[]> = {
  "*": ["class", "id"],
  a: ["href", "name", "rel", "target", "title"],
  code: ["class"],
  img: ["alt", "height", "src", "width"],
  input: ["checked", "disabled", "type"],
} as const;

/** Sanitized HTML generated by STM server Markdown rendering. */
export type VoiceNoteMarkdownHtmlInput = string | null | undefined;

/** Defense in depth for HTML crossing the widget boundary; this never parses Markdown. */
function sanitizeServerMarkdownHtml(html: string): string {
  return sanitizeHtml(html, {
    allowedTags: [...MARKDOWN_TAGS],
    allowedAttributes: MARKDOWN_ATTRIBUTES,
    allowedSchemes: ["http", "https", "mailto"],
    allowProtocolRelative: false,
    transformTags: {
      a: (tagName, attributes) => ({
        tagName,
        attribs: { ...attributes, target: "_blank", rel: "noopener noreferrer" },
      }),
    },
  });
}

/** Exported for DOM fixtures; input is server HTML, never raw Markdown. */
export function renderVoiceNoteMarkdownHtml(html: VoiceNoteMarkdownHtmlInput): string {
  return typeof html === "string" && html.trim() ? sanitizeServerMarkdownHtml(html) : "";
}

function appendSanitizedHtml(container: HTMLElement, html: string): void {
  if (!html) return;
  const parsed = new DOMParser().parseFromString(`<body>${html}</body>`, "text/html");
  container.append(
    ...Array.from(parsed.body.childNodes, (node) => document.importNode(node, true)),
  );
}

export function VoiceNoteMarkdown(props: {
  readonly html: VoiceNoteMarkdownHtmlInput | (() => VoiceNoteMarkdownHtmlInput);
  readonly compact?: boolean | (() => boolean);
}): HTMLElement {
  const container = document.createElement("div");
  container.className = "stm-voice-note-markdown";
  const getHtml = () => (typeof props.html === "function" ? props.html() : props.html);
  const getCompact = () =>
    typeof props.compact === "function" ? props.compact() : (props.compact ?? false);
  createRenderEffect(() => {
    container.classList.toggle("stm-voice-note-markdown--compact", getCompact());
    container.replaceChildren();
    appendSanitizedHtml(container, renderVoiceNoteMarkdownHtml(getHtml()));
  });
  return container;
}
