import * as stylex from "@stylexjs/stylex";

// Session header chrome shared by the session page, the notes pages, the
// session list, and the status controls. The OpenCode activity-preview styles
// live with their sole owner in OpenCodeActivityPreview.tsx.

export const session = stylex.create({
  titleRow: {
    display: "flex",
    alignItems: "center",
    rowGap: "0.8rem",
    columnGap: "0.8rem",
    minWidth: 0,
  },
  title: {
    minWidth: 0,
    maxWidth: "100%",
    overflowWrap: "anywhere",
    wordBreak: "break-word",
  },
  titleClickable: { cursor: "pointer" },
  editableTitleRow: {
    display: "flex",
    alignItems: "center",
    columnGap: "0.55rem",
    rowGap: "0.35rem",
    flexWrap: "wrap",
  },
  titleEditButton: {
    borderWidth: 0,
    borderRadius: "999px",
    paddingBlock: "0.25rem",
    paddingInline: "0.45rem",
    backgroundColor: "#efe5d7",
    color: "#17202a",
    cursor: "pointer",
    fontSize: "0.9rem",
  },
  titleEditForm: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    columnGap: "0.5rem",
    rowGap: "0.5rem",
    maxWidth: "100%",
  },
  titleEditInput: {
    font: "inherit",
    minWidth: "min(22rem, 100%)",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "rgba(23, 32, 42, 0.18)",
    borderRadius: "999px",
    paddingBlock: "0.55rem",
    paddingInline: "0.8rem",
  },
  heroTitle: {
    marginTop: "0.35rem",
    marginBottom: "0.35rem",
    fontSize: "clamp(1.75rem, 5vw, 3.5rem)",
    lineHeight: 1.05,
    fontWeight: 800,
  },
  heroTitleRow: {
    display: "flex",
    alignItems: "baseline",
    columnGap: "0.55rem",
    rowGap: "0.35rem",
    flexWrap: "wrap",
  },
  identityPrimary: {
    overflowWrap: "anywhere",
    wordBreak: "break-word",
  },
  organizePathRow: {
    display: "inline-flex",
    alignItems: "center",
    flexWrap: "wrap",
    columnGap: "0.2rem",
    rowGap: "0.15rem",
    minWidth: 0,
    maxWidth: "100%",
    fontSize: "0.72rem",
    fontWeight: 500,
    lineHeight: 1.2,
  },
  organizePathLink: {
    color: "#667085",
    textDecoration: { default: "none", ":hover": "underline" },
  },
  organizePathSep: {
    color: "#98a2b3",
  },
  copyMentionButton: {
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "rgba(23, 32, 42, 0.18)",
    borderRadius: "8px",
    paddingBlock: "0.15rem",
    paddingInline: "0.45rem",
    backgroundColor: "transparent",
    color: "#667085",
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
    fontSize: "0.72rem",
    cursor: "pointer",
  },
  providerTitleRow: {
    marginTop: 0,
  },
  providerTitleText: {
    fontSize: "0.85rem",
    color: "#888",
    overflowWrap: "anywhere",
    wordBreak: "break-word",
  },
  titleCluster: {
    display: "flex",
    flexDirection: "column",
    minWidth: 0,
  },
  idSub: {
    fontSize: "0.75rem",
    color: "#888",
    overflowWrap: "anywhere",
    wordBreak: "break-all",
  },
  noteSub: {
    display: "block",
    maxWidth: "100%",
    minHeight: "1.1rem",
    fontSize: "0.85rem",
    color: "#888",
    marginTop: "0.25rem",
    marginBottom: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    textDecoration: {
      default: "none",
      ":hover": "underline",
    },
  },
  statusControls: {
    display: "inline-flex",
    alignItems: "center",
    flexWrap: "wrap",
    rowGap: "0.45rem",
    columnGap: "0.45rem",
    minHeight: "1.55rem",
  },
  statusControlsReserved: {
    visibility: "hidden",
  },
});
