import * as stylex from "@stylexjs/stylex";

const tablet = "@media (max-width: 1050px)" as const;
const mobile = "@media (max-width: 760px)" as const;

export const explorer = stylex.create({
  layout: {
    display: { default: "grid", [mobile]: "flex" },
    gridTemplateColumns: {
      default: "245px minmax(540px, 1fr) 260px",
      [tablet]: "220px minmax(500px, 1fr)",
    },
    gridTemplateRows: { default: "none", [tablet]: "auto 1fr" },
    flexDirection: "column",
    flexGrow: 1,
    minHeight: 0,
    height: "auto",
  },
  treePanel: {
    position: { default: "static", [mobile]: "fixed" },
    zIndex: { default: "auto", [mobile]: 120 },
    top: { default: "auto", [mobile]: 0 },
    bottom: { default: "auto", [mobile]: 0 },
    left: { default: "auto", [mobile]: 0 },
    gridRow: { default: "auto", [tablet]: "1 / 3" },
    width: { default: "auto", [mobile]: "min(310px, 86vw)" },
    maxHeight: { default: "none", [mobile]: "none" },
    overflowY: "auto",
    scrollbarColor: "#4a5046 transparent",
    scrollbarWidth: "thin",
    borderRightWidth: "1px",
    borderRightStyle: "solid",
    borderRightColor: { default: "#2a2d28", [mobile]: "#393c36" },
    padding: { default: "15px 9px 80px", [mobile]: "18px 9px 80px" },
    backgroundColor: "#131512",
    boxShadow: { default: "none", [mobile]: "18px 0 50px rgba(0, 0, 0, 0.45)" },
    transform: { default: "none", [mobile]: "translateX(-105%)" },
    transition: "transform 180ms ease",
  },
  treePanelOpen: { transform: "translateX(0)" },
  treeBackdrop: {
    position: "fixed",
    zIndex: 110,
    inset: 0,
    display: { default: "none", [mobile]: "block" },
    borderWidth: 0,
    backgroundColor: "rgba(0, 0, 0, 0.6)",
    backdropFilter: "blur(3px)",
  },
  treeHeading: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    height: "38px",
    paddingBlock: "0",
    paddingInline: "8px",
  },
  eyebrow: { color: "#656960", fontSize: "11px", fontWeight: 800, letterSpacing: "0.14em" },
  treeAdd: {
    display: "flex",
    alignItems: "center",
    rowGap: "4px",
    columnGap: "4px",
    minHeight: "29px",
    borderWidth: 0,
    borderRadius: "6px",
    paddingBlock: "0",
    paddingInline: "6px",
    backgroundColor: { default: "transparent", ":hover": "#292c27" },
    color: { default: "#aeb2a9", ":hover": "#eef0e9" },
    font: "inherit",
    fontSize: "10px",
    fontWeight: 750,
    cursor: "pointer",
  },
  mobileClose: {
    display: { default: "none", [mobile]: "block" },
    borderWidth: 0,
    backgroundColor: "transparent",
    color: "#b8bbb4",
    fontSize: "22px",
    lineHeight: 1,
    cursor: "pointer",
  },
  treeRow: (depth: number) => ({
    display: "grid",
    gridTemplateColumns: "17px minmax(0, 1fr) auto 12px",
    alignItems: "center",
    gap: "5px",
    width: "100%",
    minHeight: "44px",
    borderWidth: 0,
    borderRadius: "7px",
    paddingRight: "8px",
    paddingLeft: 14 + depth * 18,
    backgroundColor: { default: "transparent", ":hover": "#292c27" },
    color: { default: "#8c9087", ":hover": "#eceee8" },
    font: "inherit",
    fontSize: "14px",
    textAlign: "left",
    cursor: "pointer",
  }),
  treeRowActive: { backgroundColor: "#292c27", color: "#eceee8", boxShadow: "inset 2px 0 #dfff45" },
  treeRowIcon: { width: "13px" },
  treeRowLabel: { display: "block" },
  treeRowDetail: {
    display: "block",
    overflow: "hidden",
    marginTop: "3px",
    color: "#686c64",
    fontSize: "9px",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  treeRowBadge: {
    borderRadius: "9px",
    paddingBlock: "3px",
    paddingInline: "5px",
    backgroundColor: "#30342e",
    color: "#92968d",
    fontSize: "7px",
    fontWeight: 850,
    letterSpacing: "0.06em",
  },
  treeRowChevron: { width: "10px", color: "#51554e" },
  treeRowMeta: { color: "#5f635b", fontSize: "12px" },
  divider: {
    height: "1px",
    marginTop: "12px",
    marginRight: "8px",
    marginBottom: "17px",
    marginLeft: "8px",
    backgroundColor: "#2a2d28",
  },
  treeSection: {
    display: "block",
    paddingTop: "0",
    paddingRight: "8px",
    paddingBottom: "8px",
    paddingLeft: "8px",
  },
  treeImport: {
    display: "flex",
    alignItems: "center",
    rowGap: "7px",
    columnGap: "7px",
    width: "calc(100% - 8px)",
    height: "35px",
    marginBlock: "15px",
    marginInline: "4px",
    borderWidth: "1px",
    borderStyle: "dashed",
    borderColor: "#383b35",
    borderRadius: "7px",
    paddingBlock: "0",
    paddingInline: "10px",
    backgroundColor: "transparent",
    color: "#73776f",
    font: "inherit",
    fontSize: "14px",
    cursor: "pointer",
  },
  archivedRow: {
    display: "grid",
    gridTemplateColumns: "16px 1fr auto",
    alignItems: "center",
    rowGap: "7px",
    columnGap: "7px",
    width: "100%",
    minHeight: "38px",
    borderWidth: 0,
    borderRadius: "7px",
    paddingBlock: "0",
    paddingInline: "10px",
    backgroundColor: { default: "transparent", ":hover": "#252824" },
    color: "#777b73",
    font: "inherit",
    fontSize: "10px",
    textAlign: "left",
    cursor: "pointer",
  },
  archivedRestore: { color: "#dfff45", fontSize: "9px" },
  treeEmpty: {
    marginTop: "8px",
    marginRight: "10px",
    marginBottom: "15px",
    marginLeft: "10px",
    color: "#666a62",
    fontSize: "10px",
  },
  main: {
    gridColumn: { default: "auto", [tablet]: "2" },
    gridRow: { default: "auto", [tablet]: "2" },
    order: { default: 0, [mobile]: 2 },
    overflowY: { default: "auto", [mobile]: "visible" },
    scrollbarColor: "#4a5046 transparent",
    scrollbarWidth: "thin",
    padding: { default: "19px 24px 100px", [mobile]: "20px 15px 115px" },
  },
  mobileActions: {
    display: { default: "contents", [mobile]: "none" },
    rowGap: "7px",
    columnGap: "7px",
    marginBottom: { default: 0, [mobile]: "15px" },
  },
  mobileNavigator: {
    display: { default: "none", [mobile]: "flex" },
    alignItems: "center",
    rowGap: "7px",
    columnGap: "7px",
    height: "35px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "#383b35",
    borderRadius: "8px",
    paddingBlock: "0",
    paddingInline: "10px",
    backgroundColor: "#1c1f1a",
    color: "#aeb1a9",
    font: "inherit",
    fontSize: "14px",
    fontWeight: 750,
    cursor: "pointer",
  },
  breadcrumb: {
    display: { default: "flex", [mobile]: "none" },
    alignItems: "center",
    rowGap: "5px",
    columnGap: "5px",
    color: "#62665e",
    fontSize: "11px",
  },
  breadcrumbIcon: { width: "9px" },
  breadcrumbStrong: { color: "#adb0a9" },
  worktreeHero: {
    display: "grid",
    gridTemplateColumns: {
      default: "48px minmax(0, 1fr) auto auto",
      [mobile]: "43px minmax(0, 1fr) auto auto",
    },
    alignItems: "start",
    rowGap: "14px",
    columnGap: "14px",
    marginTop: "27px",
  },
  branchBadge: {
    display: "grid",
    width: "47px",
    height: "47px",
    placeItems: "center",
    borderRadius: "13px",
    backgroundColor: "#292d26",
    color: "#dfff45",
  },
  worktreeLabel: { color: "#666a62", fontSize: "11px", fontWeight: 800, letterSpacing: "0.14em" },
  worktreeTitle: {
    marginTop: "5px",
    marginRight: "0",
    marginBottom: "7px",
    marginLeft: "0",
    fontSize: { default: "32px", [mobile]: "28px" },
    letterSpacing: "-0.05em",
  },
  worktreeDescription: {
    maxWidth: "480px",
    margin: 0,
    color: "#777b73",
    fontSize: "12px",
    lineHeight: 1.5,
  },
  worktreeMenu: {
    display: "grid",
    width: "30px",
    height: "30px",
    placeItems: "center",
    borderWidth: 0,
    borderRadius: "7px",
    backgroundColor: "transparent",
    color: "#696d65",
    cursor: "pointer",
  },
  gitMenuWrap: { position: "relative" },
  gitMenu: {
    position: "absolute",
    zIndex: 80,
    top: "36px",
    right: 0,
    width: "215px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "#3d413a",
    borderRadius: "10px",
    padding: "6px",
    backgroundColor: "#171a16",
    boxShadow: "0 18px 50px rgba(0, 0, 0, 0.48)",
  },
  gitMenuItem: {
    display: "grid",
    gridTemplateColumns: "18px 1fr",
    alignItems: "center",
    rowGap: "8px",
    columnGap: "8px",
    width: "100%",
    minHeight: "39px",
    borderWidth: 0,
    borderRadius: "7px",
    paddingBlock: "0",
    paddingInline: "9px",
    backgroundColor: { default: "transparent", ":hover": "#292c27" },
    color: "#b5b8b0",
    font: "inherit",
    fontSize: "12px",
    textAlign: "left",
    cursor: "pointer",
  },
  gitMenuDanger: {
    marginTop: "4px",
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: "#34372f",
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    color: "#fa8067",
  },
  pathCard: {
    display: "flex",
    alignItems: { default: "center", [mobile]: "flex-start" },
    flexWrap: { default: "nowrap", [mobile]: "wrap" },
    rowGap: "8px",
    columnGap: "8px",
    marginTop: "25px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "#2e312c",
    borderRadius: "10px",
    paddingBlock: "12px",
    paddingInline: "13px",
    backgroundColor: "#171916",
  },
  pathDetails: { width: { default: "auto", [mobile]: "100%" }, minWidth: 0, marginRight: "auto" },
  pathLabel: {
    display: "block",
    marginBottom: "4px",
    color: "#5f635b",
    fontSize: "11px",
    fontWeight: 800,
    letterSpacing: "0.13em",
  },
  pathCode: {
    overflowWrap: { default: "normal", [mobile]: "anywhere" },
    color: "#afb2aa",
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
    fontSize: "12px",
  },
  pathButton: {
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "#353832",
    borderRadius: "6px",
    paddingBlock: "6px",
    paddingInline: "8px",
    backgroundColor: "#20231f",
    color: "#8a8e85",
    font: "inherit",
    fontSize: "11px",
    cursor: "pointer",
  },
  actions: {
    display: "flex",
    flexWrap: { default: "nowrap", [mobile]: "wrap" },
    rowGap: "7px",
    columnGap: "7px",
    marginTop: "12px",
  },
  actionButton: {
    display: "flex",
    alignItems: "center",
    rowGap: "6px",
    columnGap: "6px",
    height: "34px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "#363933",
    borderRadius: "7px",
    paddingBlock: "0",
    paddingInline: "10px",
    backgroundColor: "#1b1e1a",
    color: { default: "#94988f", ":disabled": "#5d6159" },
    font: "inherit",
    fontSize: "14px",
    cursor: { default: "pointer", ":disabled": "not-allowed" },
    opacity: { default: 1, ":disabled": 0.55 },
  },
  primaryAction: {
    borderColor: "#dfff45",
    backgroundColor: "#dfff45",
    color: "#172000",
    fontWeight: 800,
  },
  sessionSection: {
    marginTop: "30px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "#2d302b",
    borderRadius: "11px",
    backgroundColor: "#161815",
  },
  panelHeading: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    minHeight: "74px",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: "#2c2f2a",
    paddingBlock: "0",
    paddingInline: "19px",
  },
  panelLabel: {
    display: "block",
    color: "#656961",
    fontSize: "11px",
    fontWeight: 800,
    letterSpacing: "0.13em",
  },
  panelTitle: {
    marginTop: "5px",
    marginRight: "0",
    marginBottom: "0",
    marginLeft: "0",
    fontSize: "24px",
    letterSpacing: "-0.04em",
  },
  panelButton: {
    display: "flex",
    alignItems: "center",
    rowGap: "5px",
    columnGap: "5px",
    borderWidth: 0,
    backgroundColor: "transparent",
    color: "#777b73",
    font: "inherit",
    fontSize: "14px",
    cursor: "pointer",
  },
  sessionCards: { padding: "7px" },
  sessionCard: {
    display: "grid",
    gridTemplateColumns: "34px 1fr auto",
    alignItems: "center",
    rowGap: "9px",
    columnGap: "9px",
    minHeight: "88px",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: "#272a25",
    paddingBlock: "8px",
    paddingInline: "10px",
  },
  sessionCardLast: { borderBottomWidth: 0 },
  sessionCardAttention: {
    marginTop: "5px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "rgba(247, 125, 97, 0.24)",
    borderRadius: "8px",
    backgroundColor: "rgba(247, 125, 97, 0.06)",
  },
  sessionTitle: { display: "block", marginTop: "5px", fontSize: "14px" },
  sessionDetail: { display: "block", marginTop: "3px", color: "#696d65", fontSize: "12px" },
  sessionOpen: {
    minWidth: 0,
    borderWidth: 0,
    padding: 0,
    backgroundColor: "transparent",
    color: "inherit",
    font: "inherit",
    textAlign: "left",
    cursor: "pointer",
  },
  sessionActions: {
    position: "relative",
    display: "flex",
    alignItems: "center",
    rowGap: "5px",
    columnGap: "5px",
  },
  sessionReply: {
    height: "30px",
    borderWidth: 0,
    borderRadius: "6px",
    paddingBlock: "0",
    paddingInline: "9px",
    backgroundColor: "#f77d61",
    color: "#26130d",
    font: "inherit",
    fontSize: "10px",
    fontWeight: 850,
    cursor: "pointer",
  },
  sessionMenuTrigger: {
    display: "grid",
    width: "30px",
    height: "30px",
    placeItems: "center",
    borderWidth: 0,
    borderRadius: "6px",
    backgroundColor: { default: "transparent", ":hover": "#292c27" },
    color: { default: "#767a72", ":hover": "#d4d6cf" },
    cursor: "pointer",
  },
  sessionMenuTriggerOpen: { backgroundColor: "#292c27", color: "#d4d6cf" },
  sessionMenu: {
    position: "absolute",
    zIndex: 80,
    top: "35px",
    right: 0,
    width: "155px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "#3a3e37",
    borderRadius: "9px",
    padding: "5px",
    backgroundColor: "#171a16",
    boxShadow: "0 14px 35px rgba(0, 0, 0, 0.45)",
  },
  sessionMenuItem: {
    display: "flex",
    alignItems: "center",
    rowGap: "8px",
    columnGap: "8px",
    width: "100%",
    height: "38px",
    borderWidth: 0,
    borderRadius: "6px",
    paddingBlock: "0",
    paddingInline: "9px",
    backgroundColor: { default: "transparent", ":hover": "#292c27" },
    color: "inherit",
    font: "inherit",
    fontSize: "12px",
    fontWeight: 750,
    textAlign: "left",
    cursor: "pointer",
  },
  sessionMenuArchive: {
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: "#30342e",
    borderTopLeftRadius: "0",
    borderTopRightRadius: "0",
    borderBottomRightRadius: "6px",
    borderBottomLeftRadius: "6px",
    color: "#c3a567",
  },
  emptySessions: {
    display: "grid",
    minHeight: "150px",
    placeItems: "center",
    alignContent: "center",
    rowGap: "7px",
    columnGap: "7px",
    color: "#6f736b",
    textAlign: "center",
  },
  emptyIcon: { width: "25px" },
  emptyTitle: { color: "#c5c8c0", fontSize: "14px" },
  emptyDetail: { fontSize: "11px" },
  contextPanel: {
    display: { default: "block", [mobile]: "none" },
    gridColumn: { default: "auto", [tablet]: "2" },
    gridRow: { default: "auto", [tablet]: "1" },
    order: { default: 0, [mobile]: 1 },
    width: { default: "auto", [mobile]: "100%" },
    overflow: "visible",
    borderBottomWidth: { default: 0, [tablet]: "1px" },
    borderBottomStyle: "solid",
    borderBottomColor: "#2a2d28",
    borderLeftWidth: { default: "1px", [tablet]: 0 },
    borderLeftStyle: "solid",
    borderLeftColor: "#2a2d28",
    padding: { default: "21px 18px 90px", [tablet]: "13px 20px", [mobile]: "14px 15px" },
    backgroundColor: "#151714",
  },
  contextHeading: { display: "flex", alignItems: "center", justifyContent: "space-between" },
  contextLabel: { color: "#686c64", fontSize: "11px", fontWeight: 800, letterSpacing: "0.14em" },
  contextActions: { display: "flex", alignItems: "center", rowGap: "7px", columnGap: "7px" },
  contextEdit: {
    borderTopWidth: "0",
    borderRightWidth: "0",
    borderBottomWidth: "1px",
    borderLeftWidth: "0",
    borderStyle: "solid",
    borderColor: "#555950",
    padding: 0,
    backgroundColor: "transparent",
    color: "#858980",
    font: "inherit",
    fontSize: "11px",
    cursor: "pointer",
  },
  contextDescription: {
    margin: { default: "18px 0 25px", [tablet]: "8px 0 0", [mobile]: "9px 0 0" },
    color: "#92968d",
    fontFamily: "ui-serif, Georgia, serif",
    fontSize: "13px",
    lineHeight: { default: 1.55, [mobile]: 1.45 },
  },
  contextBlock: {
    display: { default: "block", [tablet]: "none" },
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: "#2c2f2a",
    paddingBlock: "14px",
    paddingInline: "0",
  },
  contextBlockLabel: {
    display: "block",
    color: "#62665e",
    fontSize: "11px",
    fontWeight: 800,
    letterSpacing: "0.13em",
  },
  contextBlockTitle: { display: "block", marginTop: "6px", fontSize: "14px" },
  contextBlockDetail: { display: "block", marginTop: "3px", color: "#6b6f67", fontSize: "12px" },
  importNote: {
    display: { default: "grid", [tablet]: "none" },
    gridTemplateColumns: "20px 1fr",
    rowGap: "7px",
    columnGap: "7px",
    marginTop: "20px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "rgba(223, 255, 69, 0.17)",
    borderRadius: "9px",
    padding: "11px",
    backgroundColor: "rgba(223, 255, 69, 0.045)",
    color: "#dfff45",
  },
  importNoteText: { margin: 0, color: "#767a72", fontSize: "12px", lineHeight: 1.5 },
  importNoteTitle: { display: "block", marginBottom: "3px", color: "#b8bcb2", fontSize: "8px" },
});
