import * as stylex from "@stylexjs/stylex";

const mobile = "@media (max-width: 760px)" as const;

export const chrome = stylex.create({
  root: {
    minHeight: "100vh",
    backgroundColor: "#101210",
    color: "#eeefe9",
    fontFamily:
      "ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
  },
  shell: {
    display: { default: "grid", [mobile]: "block" },
    gridTemplateColumns: "68px 1fr",
    minHeight: "100vh",
    paddingBottom: { default: 0, [mobile]: "60px" },
    backgroundColor: "#111310",
  },
  main: {
    display: "flex",
    flexDirection: "column",
    minWidth: 0,
    height: { default: "100vh", [mobile]: "auto" },
    overflow: { default: "hidden", [mobile]: "visible" },
  },
  icon: {
    width: "18px",
    height: "18px",
    flexShrink: 0,
    fill: "none",
    stroke: "currentColor",
    strokeLinecap: "round",
    strokeLinejoin: "round",
    strokeWidth: 1.45,
  },
  iconSmall: { width: "14px" },
  sidebar: {
    position: { default: "relative", [mobile]: "fixed" },
    zIndex: { default: 20, [mobile]: 90 },
    right: { default: "auto", [mobile]: "10px" },
    bottom: { default: "auto", [mobile]: "10px" },
    left: { default: "auto", [mobile]: "10px" },
    display: { default: "flex", [mobile]: "grid" },
    gridTemplateColumns: { default: "none", [mobile]: "auto 1fr auto" },
    alignItems: "center",
    flexDirection: "column",
    height: { default: "auto", [mobile]: "52px" },
    borderWidth: { default: "0 1px 0 0", [mobile]: "1px" },
    borderStyle: "solid",
    borderColor: { default: "#2a2d28", [mobile]: "#353832" },
    borderRadius: { default: 0, [mobile]: "14px" },
    padding: { default: "18px 0", [mobile]: "7px 10px" },
    backgroundColor: "#0c0e0c",
    boxShadow: { default: "none", [mobile]: "0 15px 40px rgba(0, 0, 0, 0.5)" },
  },
  mark: {
    display: "grid",
    width: { default: "34px", [mobile]: "32px" },
    height: { default: "34px", [mobile]: "32px" },
    placeItems: "center",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "#4c5049",
    borderRadius: "50%",
    color: "#f2f3ed",
  },
  markIcon: {
    width: "23px",
    fill: "none",
    stroke: "currentColor",
    strokeLinecap: "round",
    strokeWidth: 1.6,
  },
  sidebarNav: {
    display: { default: "grid", [mobile]: "flex" },
    justifyContent: { default: "normal", [mobile]: "center" },
    gap: { default: "9px", [mobile]: "6px" },
    marginTop: { default: "56px", [mobile]: 0 },
  },
  navButton: {
    position: "relative",
    display: "grid",
    width: { default: "38px", [mobile]: "34px" },
    height: { default: "38px", [mobile]: "34px" },
    placeItems: "center",
    borderWidth: 0,
    borderRadius: "10px",
    backgroundColor: { default: "transparent", ":hover": "#282b26" },
    color: { default: "#73776f", ":hover": "#f2f3ed" },
    font: "inherit",
    textDecoration: "none",
    cursor: "pointer",
  },
  navButtonActive: { backgroundColor: "#282b26", color: "#f2f3ed" },
  navActiveIndicator: {
    position: "absolute",
    left: "-15px",
    display: { default: "block", [mobile]: "none" },
    width: "2px",
    height: "19px",
    backgroundColor: "#dfff45",
  },
  alertDot: {
    position: "absolute",
    top: "6px",
    right: "6px",
    width: "6px",
    height: "6px",
    borderWidth: "2px",
    borderStyle: "solid",
    borderColor: "#111310",
    borderRadius: "50%",
    backgroundColor: "#fa795f",
  },
  user: {
    display: "grid",
    width: { default: "34px", [mobile]: "32px" },
    height: { default: "34px", [mobile]: "32px" },
    marginTop: { default: "auto", [mobile]: 0 },
    placeItems: "center",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "#464943",
    borderRadius: "50%",
    backgroundColor: "#252824",
    color: "#b9bcb4",
    fontSize: "9px",
    fontWeight: 800,
    textDecoration: "none",
  },
  userActive: {
    borderColor: "#dfff45",
    color: "#f3f5ee",
    boxShadow: "0 0 0 3px rgba(223, 255, 69, 0.08)",
  },
  topbar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    height: { default: "78px", [mobile]: "66px" },
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: "#2a2d28",
    padding: { default: "0 28px", [mobile]: "0 15px" },
    backgroundColor: "rgba(17, 19, 16, 0.9)",
  },
  topbarLabel: {
    display: "block",
    marginBottom: "4px",
    color: "#656960",
    fontSize: "11px",
    fontWeight: 800,
    letterSpacing: "0.15em",
  },
  topbarTitle: { display: "block", fontSize: "24px", letterSpacing: "-0.025em" },
  topActions: { display: "flex", alignItems: "center", rowGap: "8px", columnGap: "8px" },
  searchButton: {
    display: { default: "flex", [mobile]: "none" },
    alignItems: "center",
    rowGap: "8px",
    columnGap: "8px",
    minWidth: "190px",
    height: "36px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "#343731",
    borderRadius: "9px",
    paddingBlock: "0",
    paddingInline: "9px",
    backgroundColor: "#181b17",
    color: "#73776f",
    font: "inherit",
    fontSize: "14px",
    textAlign: "left",
    textDecoration: "none",
    cursor: "pointer",
  },
  searchShortcut: {
    marginLeft: "auto",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "#393c36",
    borderRadius: "4px",
    paddingBlock: "2px",
    paddingInline: "5px",
    color: "#62665f",
    fontSize: "8px",
  },
  iconButton: {
    position: "relative",
    display: { default: "grid", [mobile]: "none" },
    width: "38px",
    height: "38px",
    placeItems: "center",
    borderWidth: 0,
    borderRadius: "10px",
    backgroundColor: "transparent",
    color: "#73776f",
    cursor: "pointer",
  },
  avatar: {
    display: "grid",
    flexGrow: "0",
    flexShrink: "0",
    flexBasis: "auto",
    width: "32px",
    height: "32px",
    placeItems: "center",
    borderRadius: "9px",
    fontSize: "9px",
    fontWeight: 900,
  },
  lime: { backgroundColor: "#dfff45", color: "#182000" },
  coral: { backgroundColor: "#f77d61", color: "#29140e" },
  blue: { backgroundColor: "#7888ff", color: "#11152c" },
  purple: { backgroundColor: "#8e75ef", color: "#171028" },
  status: {
    display: "inline-flex",
    alignItems: "center",
    rowGap: "5px",
    columnGap: "5px",
    width: "max-content",
    color: "#82e99a",
    fontSize: "11px",
    fontWeight: 750,
    whiteSpace: "nowrap",
  },
  statusAttention: { color: "#ff8a71" },
  statusWaiting: { color: "#e8b75f" },
  statusDot: {
    width: "5px",
    height: "5px",
    borderRadius: "50%",
    backgroundColor: "currentColor",
    boxShadow: "0 0 8px currentColor",
  },
});

export const menu = stylex.create({
  wrap: { position: "relative" },
  trigger: {
    display: "grid",
    width: "36px",
    height: "36px",
    placeItems: "center",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: { default: "#3a3d37", ":hover": "#565b51" },
    borderRadius: "8px",
    backgroundColor: { default: "#1b1e1a", ":hover": "#292d27" },
    color: "#b4b7b0",
    cursor: "pointer",
  },
  triggerOpen: { borderColor: "#565b51", backgroundColor: "#292d27" },
  triggerCompact: { width: "29px", height: "27px", borderRadius: "7px", color: "#969a91" },
  popup: {
    position: { default: "absolute", [mobile]: "fixed" },
    zIndex: 150,
    top: { default: "44px", [mobile]: "58px" },
    right: { default: 0, [mobile]: "10px" },
    left: { default: "auto", [mobile]: "10px" },
    width: { default: "270px", [mobile]: "auto" },
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "#3d413a",
    borderRadius: "12px",
    padding: "7px",
    backgroundColor: "#171a16",
    boxShadow: "0 18px 50px rgba(0, 0, 0, 0.48)",
  },
  contextPopup: { position: "fixed", zIndex: 210, right: "auto", left: "auto" },
  heading: {
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: "#2e322c",
    paddingTop: "8px",
    paddingRight: "9px",
    paddingBottom: "11px",
    paddingLeft: "9px",
  },
  headingLabel: {
    display: "block",
    color: "#676b63",
    fontSize: "8px",
    fontWeight: 850,
    letterSpacing: "0.13em",
  },
  headingTitle: { display: "block", marginTop: "4px", fontSize: "12px" },
  item: {
    display: "grid",
    gridTemplateColumns: "20px 1fr",
    alignItems: "center",
    rowGap: "8px",
    columnGap: "8px",
    width: "100%",
    minHeight: "50px",
    borderWidth: 0,
    borderRadius: "7px",
    paddingBlock: "7px",
    paddingInline: "9px",
    backgroundColor: { default: "transparent", ":hover": "#272a25" },
    color: "inherit",
    font: "inherit",
    textAlign: "left",
    cursor: "pointer",
  },
  itemDisabled: {
    cursor: "not-allowed",
    opacity: 0.45,
    backgroundColor: { default: "transparent", ":hover": "transparent" },
  },
  itemIcon: { width: "15px", color: "#7d8178" },
  itemText: { display: "block" },
  itemTitle: { display: "block", fontSize: "12px" },
  itemDetail: { display: "block", marginTop: "3px", color: "#70746c", fontSize: "10px" },
  resetIcon: { color: "#858980", fontSize: "17px", textAlign: "center" },
  danger: {
    marginTop: "4px",
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: "#33362f",
    borderTopLeftRadius: "0",
    borderTopRightRadius: "0",
    borderBottomRightRadius: "7px",
    borderBottomLeftRadius: "7px",
    color: "#fa8067",
  },
  dangerIcon: { fontSize: "18px", textAlign: "center" },
});
