import * as stylex from "@stylexjs/stylex";

const mobile = "@media (max-width: 760px)" as const;

const modalBase = {
  position: "relative" as const,
  zIndex: 1,
  borderWidth: "1px",
  borderStyle: "solid" as const,
  borderColor: "#41453d",
  borderRadius: "15px",
  backgroundColor: "#171a16",
  color: "#eef0e9",
  boxShadow: "0 30px 90px rgba(0, 0, 0, 0.55)",
};

export const dialogs = stylex.create({
  layer: {
    position: "fixed",
    zIndex: 200,
    inset: 0,
    height: "100dvh",
    display: "grid",
    alignItems: { default: "center", [mobile]: "start" },
    justifyItems: "center",
    overflow: "hidden",
    padding: {
      default: "24px",
      [mobile]: "max(8px, env(safe-area-inset-top)) 8px 8px",
    },
  },
  backdrop: {
    position: "absolute",
    inset: 0,
    borderWidth: 0,
    backgroundColor: "rgba(5, 6, 5, 0.75)",
    backdropFilter: "blur(7px)",
    cursor: "pointer",
  },
  formModal: {
    ...modalBase,
    width: { default: "min(470px, 100%)", [mobile]: "100%" },
    maxHeight: { default: "calc(100vh - 48px)", [mobile]: "calc(100dvh - 16px)" },
    overflowY: "auto",
    scrollbarColor: "#4a5046 transparent",
    scrollbarWidth: "thin",
    padding: { default: "23px", [mobile]: "19px" },
  },
  moveModal: {
    ...modalBase,
    display: "flex",
    flexDirection: "column",
    width: { default: "min(520px, 100%)", [mobile]: "100%" },
    maxHeight: { default: "calc(100vh - 48px)", [mobile]: "calc(100dvh - 16px)" },
    overflow: "hidden",
    padding: { default: "23px", [mobile]: "19px" },
  },
  moveModalBody: {
    display: "flex",
    flexDirection: "column",
    flexGrow: 1,
    flexShrink: 1,
    minHeight: 0,
    overflowY: "auto",
    scrollbarColor: "#4a5046 transparent",
    scrollbarWidth: "thin",
    paddingRight: "2px",
  },
  moveModalFooterSticky: {
    flexShrink: 0,
    marginTop: "14px",
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: "#30332e",
    paddingTop: "14px",
  },
  pickerModal: {
    ...modalBase,
    display: "flex",
    flexDirection: "column",
    width: { default: "min(520px, 100%)", [mobile]: "100%" },
    maxHeight: { default: "calc(100vh - 48px)", [mobile]: "calc(100dvh - 16px)" },
    overflow: "hidden",
    padding: { default: "23px", [mobile]: "19px" },
  },
  importModal: { height: { default: "auto", [mobile]: "calc(100dvh - 16px)" } },
  header: { display: "flex", alignItems: "start", justifyContent: "space-between" },
  eyebrow: { color: "#777b73", fontSize: "10px", fontWeight: 850, letterSpacing: "0.13em" },
  title: {
    marginTop: "6px",
    marginRight: "0",
    marginBottom: "0",
    marginLeft: "0",
    color: "#f4f5f0",
    fontSize: "24px",
    letterSpacing: "-0.045em",
    lineHeight: 1.2,
  },
  close: {
    borderWidth: 0,
    backgroundColor: "transparent",
    color: "#8c9087",
    font: "inherit",
    fontSize: "24px",
    lineHeight: 1,
    cursor: "pointer",
  },
  description: {
    marginTop: "11px",
    marginRight: "0",
    marginBottom: "18px",
    marginLeft: "0",
    color: "#7e8279",
    fontSize: "12px",
  },
  error: {
    marginTop: "14px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "rgba(255, 126, 109, 0.45)",
    borderRadius: "8px",
    paddingBlock: "10px",
    paddingInline: "11px",
    backgroundColor: "rgba(255, 126, 109, 0.1)",
    color: "#ffb0a5",
    fontSize: "12px",
    lineHeight: 1.4,
  },
  label: { display: "block", marginTop: "21px" },
  labelText: {
    display: "block",
    color: "#777b73",
    fontSize: "10px",
    fontWeight: 850,
    letterSpacing: "0.13em",
  },
  input: {
    width: "100%",
    height: "45px",
    marginTop: "8px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: { default: "#3b3f38", ":focus": "#dfff45" },
    borderRadius: "8px",
    paddingBlock: "0",
    paddingInline: "12px",
    outline: "none",
    backgroundColor: "#101210",
    color: "#f0f1eb",
    font: "inherit",
    fontSize: "14px",
    boxShadow: { default: "none", ":focus": "0 0 0 3px rgba(223, 255, 69, 0.08)" },
  },
  textarea: {
    height: "88px",
    paddingBlock: "11px",
    resize: "vertical",
    lineHeight: 1.45,
  },
  formHelp: {
    marginTop: "16px",
    marginRight: "0",
    marginBottom: "0",
    marginLeft: "0",
    color: "#777b73",
    fontSize: "11px",
    lineHeight: 1.5,
  },
  optional: {
    marginLeft: "5px",
    color: "#555a51",
    fontSize: "8px",
    fontStyle: "normal",
    letterSpacing: "0.08em",
  },
  repoChoices: {
    display: "grid",
    gridTemplateColumns: { default: "1fr 1fr", [mobile]: "1fr" },
    rowGap: "8px",
    columnGap: "8px",
    marginBottom: "6px",
  },
  repoChoice: {
    display: "grid",
    gridTemplateColumns: "29px minmax(0, 1fr)",
    alignItems: "center",
    rowGap: "9px",
    columnGap: "9px",
    minWidth: 0,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "#343832",
    borderRadius: "9px",
    padding: "10px",
    backgroundColor: { default: "#1b1e1a", ":hover": "#232720" },
    color: "#d6d9d1",
    font: "inherit",
    textAlign: "left",
    cursor: "pointer",
  },
  repoChoiceSelected: {
    borderColor: "rgba(223, 255, 69, 0.65)",
    backgroundColor: "rgba(223, 255, 69, 0.055)",
  },
  repoChoiceIcon: {
    display: "grid",
    width: "29px",
    height: "29px",
    placeItems: "center",
    borderRadius: "7px",
    backgroundColor: "#292d26",
    color: "#dfff45",
  },
  repoChoiceTitle: { display: "block", fontSize: "12px" },
  repoChoicePath: {
    display: "block",
    overflow: "hidden",
    marginTop: "3px",
    color: "#73776f",
    fontSize: "9px",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  destinationPreview: {
    marginTop: "18px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "#30342e",
    borderRadius: "9px",
    padding: "12px",
    backgroundColor: "#101210",
  },
  destinationPath: {
    display: "block",
    overflowWrap: "anywhere",
    marginTop: "7px",
    color: "#dfff45",
    fontSize: "12px",
    lineHeight: 1.45,
  },
  destinationHint: {
    display: "block",
    marginTop: "7px",
    color: "#686c64",
    fontSize: "10px",
    lineHeight: 1.4,
  },
  footer: {
    display: "flex",
    justifyContent: "flex-end",
    rowGap: "8px",
    columnGap: "8px",
    marginTop: "23px",
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: "#30332e",
    paddingTop: "17px",
  },
  moveFooter: { marginTop: "18px", borderTopWidth: 0, paddingTop: 0 },
  button: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    rowGap: "7px",
    columnGap: "7px",
    minHeight: "39px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: { default: "#3b3e38", ":disabled": "#30332e" },
    borderRadius: "8px",
    paddingBlock: "0",
    paddingInline: "14px",
    backgroundColor: { default: "transparent", ":hover": "#232720", ":disabled": "transparent" },
    color: { default: "#e8ebe3", ":disabled": "#6a6e66" },
    font: "inherit",
    fontSize: "12px",
    fontWeight: 750,
    cursor: { default: "pointer", ":disabled": "not-allowed" },
    opacity: { default: 1, ":disabled": 0.55 },
    outlineWidth: { default: 0, ":focus-visible": "2px" },
    outlineStyle: { default: "none", ":focus-visible": "solid" },
    outlineColor: { default: "transparent", ":focus-visible": "#dfff45" },
    outlineOffset: { default: 0, ":focus-visible": "2px" },
  },
  primaryButton: {
    borderColor: { default: "#dfff45", ":disabled": "#6a7220" },
    backgroundColor: { default: "#dfff45", ":hover": "#e8ff6a", ":disabled": "#6a7220" },
    color: { default: "#182000", ":disabled": "#3a4200" },
  },
  disabledButton: { cursor: "not-allowed", opacity: 0.55 },
  searchWrap: { position: "relative", marginBottom: "10px" },
  searchField: {
    display: "grid",
    gridTemplateColumns: "20px 1fr auto",
    alignItems: "center",
    rowGap: "7px",
    columnGap: "7px",
    height: "44px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: { default: "#3b3f38", ":focus-within": "#dfff45" },
    borderRadius: "8px",
    paddingBlock: "0",
    paddingInline: "10px",
    backgroundColor: "#101210",
    boxShadow: { default: "none", ":focus-within": "0 0 0 3px rgba(223, 255, 69, 0.07)" },
  },
  searchIcon: { width: "16px", color: "#73776f" },
  searchInput: {
    minWidth: 0,
    borderWidth: 0,
    outline: "none",
    backgroundColor: "transparent",
    color: "#eef0e9",
    font: "inherit",
    fontSize: "13px",
    "::placeholder": { color: "#62665e" },
  },
  clearSearch: {
    display: "grid",
    width: "25px",
    height: "25px",
    placeItems: "center",
    borderWidth: 0,
    borderRadius: "5px",
    backgroundColor: "#292c27",
    color: "#8d9188",
    fontSize: "16px",
    cursor: "pointer",
  },
  results: {
    maxHeight: "225px",
    overflowY: "auto",
    scrollbarColor: "#4a5046 transparent",
    scrollbarWidth: "thin",
    marginTop: "6px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "#3a3e37",
    borderRadius: "8px",
    padding: "5px",
    backgroundColor: "#141713",
    boxShadow: "0 14px 35px rgba(0, 0, 0, 0.35)",
  },
  result: {
    display: "grid",
    gridTemplateColumns: "22px 1fr auto",
    alignItems: "center",
    rowGap: "8px",
    columnGap: "8px",
    width: "100%",
    minHeight: "50px",
    borderWidth: 0,
    borderRadius: "6px",
    paddingBlock: "6px",
    paddingInline: "9px",
    backgroundColor: { default: "transparent", ":hover": "#292c27" },
    color: "#eef0e9",
    font: "inherit",
    textAlign: "left",
    cursor: "pointer",
  },
  resultActive: { backgroundColor: "#292c27", color: "#f4f5f0" },
  resultIcon: { width: "15px", color: "#7c8077" },
  resultTitle: { display: "block", color: "#f0f1eb", fontSize: "12px" },
  resultPath: { display: "block", marginTop: "3px", color: "#8b8f86", fontSize: "10px" },
  currentBadge: {
    borderRadius: "10px",
    paddingBlock: "3px",
    paddingInline: "6px",
    backgroundColor: "#30342e",
    color: "#999d94",
    fontSize: "8px",
    fontStyle: "normal",
    fontWeight: 800,
  },
  checkoutBadge: {
    borderRadius: "9px",
    paddingBlock: "3px",
    paddingInline: "6px",
    backgroundColor: "#30342e",
    color: "#92968d",
    fontSize: "7px",
    fontStyle: "normal",
    fontWeight: 850,
    letterSpacing: "0.06em",
  },
  noResults: {
    display: "grid",
    minHeight: "70px",
    placeItems: "center",
    color: "#696d65",
    fontSize: "11px",
  },
  pickerSearch: { marginTop: "18px" },
  importFilters: {
    display: "grid",
    gridTemplateColumns: { default: "minmax(0, 1fr) 155px", [mobile]: "1fr" },
    rowGap: "9px",
    columnGap: "9px",
  },
  importProvider: { height: "44px", marginTop: 0 },
  pickerList: {
    display: "grid",
    flexGrow: 1,
    flexShrink: 1,
    alignContent: "start",
    gridAutoRows: "max-content",
    rowGap: "5px",
    columnGap: "5px",
    minHeight: 0,
    maxHeight: { default: "390px", [mobile]: "min(52vh, 430px)" },
    overflowY: "auto",
    scrollbarColor: "#4a5046 transparent",
    scrollbarWidth: "thin",
    marginTop: "10px",
    paddingRight: "3px",
  },
  pickerRow: {
    display: "grid",
    gridTemplateColumns: "31px minmax(0, 1fr) auto",
    alignItems: "center",
    rowGap: "10px",
    columnGap: "10px",
    width: "100%",
    minHeight: "58px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "transparent",
    borderRadius: "9px",
    paddingBlock: "7px",
    paddingInline: "9px",
    backgroundColor: { default: "transparent", ":hover": "#252824" },
    color: "inherit",
    font: "inherit",
    textAlign: "left",
    cursor: "pointer",
  },
  pickerRowSelected: {
    borderColor: "rgba(223, 255, 69, 0.35)",
    backgroundColor: "rgba(223, 255, 69, 0.045)",
  },
  pickerRowActive: {
    borderColor: "rgba(223, 255, 69, 0.6)",
    backgroundColor: "rgba(223, 255, 69, 0.075)",
  },
  pickerIcon: {
    display: "grid",
    width: "29px",
    height: "29px",
    placeItems: "center",
    borderRadius: "7px",
    backgroundColor: "#272b25",
    color: "#a9ada4",
  },
  pickerTitle: { display: "block", fontSize: "13px" },
  pickerPath: {
    display: "block",
    overflow: "hidden",
    marginTop: "3px",
    color: "#6f736b",
    fontSize: "10px",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  pickerFooter: {
    display: "flex",
    marginTop: "14px",
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: "#30332e",
    paddingTop: "14px",
  },
  pickerFooterSplit: { justifyContent: "space-between", rowGap: "8px", columnGap: "8px" },
  gitPickerList: { rowGap: "9px", columnGap: "9px" },
  importList: { maxHeight: { default: "430px", [mobile]: "none" } },
  importRow: {
    display: "grid",
    gridTemplateColumns: "34px minmax(0, 1fr) auto",
    alignItems: "center",
    rowGap: "10px",
    columnGap: "10px",
    minHeight: "68px",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: "#292d27",
    paddingBlock: "8px",
    paddingInline: "4px",
  },
  importDetails: { minWidth: 0 },
  gitGroup: {
    overflow: "hidden",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "#30342e",
    borderRadius: "10px",
    backgroundColor: "#131512",
  },
  gitRepoRow: {
    display: "grid",
    gridTemplateColumns: "31px minmax(0, 1fr)",
    alignItems: "center",
    rowGap: "9px",
    columnGap: "9px",
    width: "100%",
    minHeight: "50px",
    borderWidth: 0,
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: "#2e312c",
    paddingBlock: "7px",
    paddingInline: "10px",
    backgroundColor: { default: "#1b1e1a", ":hover": "#252824" },
    color: "#d3d6ce",
    font: "inherit",
    fontSize: "12px",
    textAlign: "left",
    cursor: "pointer",
  },
  gitWorktreeRow: {
    display: "grid",
    gridTemplateColumns: "31px minmax(0, 1fr) auto",
    alignItems: "center",
    rowGap: "9px",
    columnGap: "9px",
    width: "100%",
    minHeight: "47px",
    borderWidth: 0,
    borderRadius: 0,
    paddingBlock: "6px",
    paddingRight: "10px",
    paddingLeft: "25px",
    backgroundColor: { default: "transparent", ":hover": "#252824" },
    color: "#aeb2a9",
    font: "inherit",
    fontSize: "12px",
    textAlign: "left",
    cursor: "pointer",
  },
  breadcrumb: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    rowGap: "4px",
    columnGap: "4px",
    minHeight: "38px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "#33372f",
    borderRadius: "8px",
    paddingBlock: "6px",
    paddingInline: "8px",
    backgroundColor: "#101210",
  },
  breadcrumbPart: { display: "flex", alignItems: "center", rowGap: "4px", columnGap: "4px" },
  breadcrumbSeparator: { color: "#51554e", fontStyle: "normal" },
  breadcrumbButton: {
    borderWidth: 0,
    borderRadius: "4px",
    paddingBlock: "4px",
    paddingInline: "6px",
    backgroundColor: "transparent",
    color: "#858980",
    font: "inherit",
    fontSize: "11px",
    cursor: "pointer",
  },
  breadcrumbCurrent: { backgroundColor: "#292c27", color: "#eef0e9" },
  moveList: {
    minHeight: 0,
    maxHeight: "260px",
    overflowY: "auto",
    scrollbarColor: "#4a5046 transparent",
    scrollbarWidth: "thin",
    marginTop: "10px",
    marginRight: "0",
    marginBottom: "0",
    marginLeft: "0",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "#33372f",
    borderRadius: "8px",
    padding: "5px",
    listStyle: "none",
  },
  moveItem: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    height: "43px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "transparent",
    borderRadius: "6px",
    paddingBlock: "0",
    paddingInline: "10px",
    backgroundColor: { default: "transparent", ":hover": "#292c27" },
    color: "#eef0e9",
    font: "inherit",
    fontSize: "12px",
    fontWeight: 750,
    cursor: "pointer",
    outlineWidth: { default: 0, ":focus-visible": "2px" },
    outlineStyle: { default: "none", ":focus-visible": "solid" },
    outlineColor: { default: "transparent", ":focus-visible": "#dfff45" },
    outlineOffset: { default: 0, ":focus-visible": "1px" },
  },
  moveItemSelected: {
    borderColor: "rgba(223, 255, 69, 0.55)",
    backgroundColor: "rgba(223, 255, 69, 0.08)",
    color: "#f7f8f3",
  },
  moveItemName: {
    display: "flex",
    alignItems: "center",
    rowGap: "8px",
    columnGap: "8px",
    color: "inherit",
  },
  moveItemDrill: {
    display: "grid",
    width: "28px",
    height: "28px",
    placeItems: "center",
    borderWidth: 0,
    borderRadius: "6px",
    backgroundColor: { default: "transparent", ":hover": "#343832" },
    color: "#a7aba2",
    font: "inherit",
    fontSize: "16px",
    cursor: "pointer",
  },
  moveItemRow: {
    display: "flex",
    alignItems: "center",
    columnGap: "4px",
  },
  moveItemSelect: {
    flexGrow: 1,
    flexShrink: 1,
    minWidth: 0,
  },
  emptyMoveList: {
    display: "grid",
    minHeight: "36px",
    placeItems: "center",
    color: "#8b8f86",
    fontSize: "11px",
  },
  cwdBlock: {
    marginTop: "10px",
    marginBottom: "0",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "#30342e",
    borderRadius: "8px",
    paddingBlock: "10px",
    paddingInline: "12px",
    backgroundColor: "#101210",
  },
  cwdLabel: {
    display: "block",
    color: "#777b73",
    fontSize: "10px",
    fontWeight: 850,
    letterSpacing: "0.13em",
  },
  cwdPath: {
    display: "block",
    overflowWrap: "anywhere",
    marginTop: "6px",
    color: "#dfff45",
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, Liberation Mono, monospace",
    fontSize: "12px",
    lineHeight: 1.4,
  },
});
