import * as stylex from "@stylexjs/stylex";

const mobile = "@media (max-width: 760px)" as const;

export const spaceHeader = stylex.create({
  root: {
    flexShrink: 0,
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: "#2a2d28",
    margin: { default: "-19px -24px 20px", [mobile]: "-20px -15px 18px" },
    padding: { default: "20px 24px 18px", [mobile]: "12px 15px 17px" },
    backgroundColor: "#111310",
  },
  commandBar: {
    display: { default: "none", [mobile]: "flex" },
    alignItems: "center",
    justifyContent: "space-between",
    rowGap: "12px",
    columnGap: "12px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "#353932",
    borderRadius: "10px",
    paddingTop: "6px",
    paddingRight: "7px",
    paddingBottom: "6px",
    paddingLeft: "11px",
    backgroundColor: "#171a16",
  },
  breadcrumb: {
    display: "flex",
    alignItems: "center",
    minWidth: 0,
    rowGap: "6px",
    columnGap: "6px",
    color: "#777b73",
    fontSize: { default: "11px", [mobile]: "10px" },
  },
  breadcrumbItem: { whiteSpace: "nowrap" },
  breadcrumbButton: {
    borderWidth: 0,
    borderRadius: "4px",
    paddingBlock: "3px",
    paddingInline: "2px",
    backgroundColor: { default: "transparent", ":hover": "#292c27" },
    color: "inherit",
    font: "inherit",
    cursor: "pointer",
  },
  breadcrumbSeparator: { color: "#484c45" },
  breadcrumbCurrent: {
    overflow: "hidden",
    color: "#d9dbd4",
    fontWeight: 800,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  switchButton: {
    display: "flex",
    flexShrink: 0,
    alignItems: "center",
    rowGap: "7px",
    columnGap: "7px",
    height: "34px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "#3a3e37",
    borderRadius: "8px",
    paddingInline: "10px",
    backgroundColor: { default: "#181b17", ":hover": "#242822" },
    color: "#c1c4bc",
    font: "inherit",
    fontSize: "11px",
    fontWeight: 750,
    cursor: "pointer",
  },
  switchLabelExtra: {
    display: { default: "inline", [mobile]: "none" },
  },
  compactSearchButton: {
    display: "flex",
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
    rowGap: "7px",
    columnGap: "7px",
    minWidth: { default: "160px", [mobile]: "48px" },
    width: { default: "auto", [mobile]: "48px" },
    height: "34px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "#3a3e37",
    borderRadius: "8px",
    paddingInline: { default: "10px", [mobile]: "0" },
    backgroundColor: { default: "#181b17", ":hover": "#242822" },
    color: "#c1c4bc",
    font: "inherit",
    fontSize: "11px",
    fontWeight: 750,
    cursor: "pointer",
  },
  compactSearchLabel: {
    display: { default: "inline", [mobile]: "none" },
  },
  commandActions: {
    display: "flex",
    flexShrink: 0,
    alignItems: "center",
    columnGap: "8px",
  },
  searchButton: {
    display: "flex",
    flexShrink: 0,
    alignItems: "center",
    columnGap: "8px",
    minWidth: "160px",
    height: "36px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "#343731",
    borderRadius: "9px",
    paddingInline: "9px",
    backgroundColor: { default: "#181b17", ":hover": "#242822" },
    color: "#73776f",
    font: "inherit",
    fontSize: "14px",
    cursor: "pointer",
  },
  searchShortcut: {
    marginLeft: "auto",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "#393c36",
    borderRadius: "4px",
    paddingBlock: "2px",
    paddingInline: "5px",
    color: "#62665f",
    fontSize: "8px",
  },
  desktopActions: {
    display: { default: "flex", [mobile]: "none" },
    flexShrink: 0,
    alignItems: "center",
  },
  body: { paddingInline: { default: "4px", [mobile]: 0 } },
  identityRow: {
    display: "flex",
    alignItems: "start",
    justifyContent: "space-between",
    rowGap: "15px",
    columnGap: "15px",
    marginTop: "11px",
  },
  identity: { minWidth: 0 },
  title: {
    margin: 0,
    color: "#f0f1ec",
    fontSize: { default: "27px", [mobile]: "29px" },
    fontWeight: 720,
    letterSpacing: "-0.045em",
    lineHeight: 1.05,
  },
  description: {
    maxWidth: "720px",
    marginTop: "7px",
    marginRight: "0",
    marginBottom: "0",
    marginLeft: "0",
    color: "#898d84",
    fontFamily: "ui-serif, Georgia, serif",
    fontSize: { default: "12px", [mobile]: "13px" },
    lineHeight: 1.5,
  },
  mobileActions: { display: { default: "none", [mobile]: "block" } },
  gitContextChip: {
    display: "grid",
    gridTemplateColumns: "29px minmax(0, auto) auto 14px",
    alignItems: "center",
    columnGap: "8px",
    width: "max-content",
    maxWidth: "100%",
    minHeight: "41px",
    marginTop: "13px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "#30342e",
    borderRadius: "999px",
    paddingTop: "5px",
    paddingRight: "9px",
    paddingBottom: "5px",
    paddingLeft: "5px",
    backgroundColor: { default: "#171a16", ":hover": "#20231e" },
    color: "#aeb2a8",
    font: "inherit",
    textAlign: "left",
    cursor: "pointer",
  },
  gitContextIcon: {
    display: "grid",
    width: "29px",
    height: "29px",
    placeItems: "center",
    borderRadius: "50%",
    backgroundColor: "#282c25",
    color: "#b6bbb1",
  },
  gitContextCopy: { display: "block", minWidth: 0 },
  gitContextLabel: {
    display: "block",
    color: "#686d64",
    fontSize: "7px",
    fontWeight: 850,
    letterSpacing: "0.12em",
  },
  gitContextValue: {
    display: "block",
    overflow: "hidden",
    marginTop: "1px",
    color: "#c7cbc1",
    fontSize: "10px",
    fontWeight: 750,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  gitContextMeta: {
    overflow: "hidden",
    color: "#747970",
    fontSize: "9px",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
});
