import * as stylex from "@stylexjs/stylex";

const tablet = "@media (max-width: 900px)" as const;
const mobile = "@media (max-width: 600px)" as const;
const motion = "@media (prefers-reduced-motion: no-preference)" as const;

const float = stylex.keyframes({
  "0%, 100%": { transform: "translate(-50%, -50%)" },
  "50%": { transform: "translate(-50%, calc(-50% - 8px))" },
});

const driftOne = stylex.keyframes({
  "0%, 100%": { transform: "rotate(-2deg) translateY(0)" },
  "50%": { transform: "rotate(-1deg) translateY(-7px)" },
});

const driftTwo = stylex.keyframes({
  "0%, 100%": { transform: "rotate(2deg) translateY(0)" },
  "50%": { transform: "rotate(1deg) translateY(8px)" },
});

export const styles = stylex.create({
  root: {
    minHeight: "100vh",
    color: "#171817",
    backgroundColor: "#f4f1e9",
    fontFamily:
      'ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
  },
  page: {
    position: "relative",
    minHeight: "100vh",
    overflow: "hidden",
  },
  signal: {
    backgroundColor: "#101210",
    backgroundImage:
      "radial-gradient(circle at 72% 46%, rgba(116, 88, 255, 0.16), transparent 29%)",
    color: "#f4f4ed",
  },
  nav: {
    position: "relative",
    zIndex: 20,
    display: "grid",
    gridTemplateColumns: {
      default: "1fr auto 1fr",
      [tablet]: "1fr auto",
    },
    alignItems: "center",
    width: {
      default: "min(1440px, calc(100% - 72px))",
      [tablet]: "calc(100% - 36px)",
    },
    height: {
      default: "88px",
      [tablet]: "72px",
    },
    marginBlock: "0",
    marginInline: "auto",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: "rgba(255, 255, 255, 0.13)",
  },
  logo: {
    display: "inline-flex",
    alignItems: "center",
    justifySelf: "start",
    rowGap: "10px",
    columnGap: "10px",
    color: "inherit",
    font: "inherit",
    fontSize: "15px",
    fontWeight: 780,
    letterSpacing: "-0.02em",
    textDecoration: "none",
  },
  logoMark: {
    display: "grid",
    width: "30px",
    height: "30px",
    placeItems: "center",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "currentColor",
    borderRadius: "50%",
  },
  markIcon: {
    width: "21px",
    fill: "none",
    stroke: "currentColor",
    strokeLinecap: "round",
    strokeWidth: 1.7,
  },
  navCenter: {
    display: {
      default: "flex",
      [tablet]: "none",
    },
    rowGap: "34px",
    columnGap: "34px",
  },
  navLink: {
    color: "inherit",
    font: "inherit",
    fontSize: "12px",
    fontWeight: 650,
    letterSpacing: "0.04em",
    textDecoration: "none",
  },
  navAction: {
    display: "inline-flex",
    alignItems: "center",
    justifySelf: "end",
    rowGap: "10px",
    columnGap: "10px",
    borderWidth: 0,
    backgroundColor: "transparent",
    color: "inherit",
    font: "inherit",
    fontSize: {
      default: "12px",
      [mobile]: 0,
    },
    fontWeight: 750,
    textDecoration: "none",
  },
  arrowIcon: {
    width: {
      default: "18px",
      [mobile]: "23px",
    },
    fill: "none",
    stroke: "currentColor",
    strokeLinecap: "round",
    strokeLinejoin: "round",
    strokeWidth: 1.5,
  },
  buttonArrowIcon: {
    width: "18px",
  },
  hero: {
    display: "grid",
    gridTemplateColumns: {
      default: "minmax(360px, 0.86fr) minmax(570px, 1.14fr)",
      [tablet]: "1fr",
    },
    alignItems: "center",
    width: {
      default: "min(1440px, calc(100% - 72px))",
      [tablet]: "calc(100% - 36px)",
    },
    minHeight: "calc(100vh - 138px)",
    marginBlock: "0",
    marginInline: "auto",
    padding: {
      default: "50px 0 90px",
      [tablet]: "50px 0 90px",
    },
  },
  copy: {
    position: "relative",
    zIndex: 5,
    maxWidth: {
      default: "650px",
      [tablet]: "620px",
    },
  },
  kicker: {
    display: "flex",
    alignItems: "center",
    rowGap: "10px",
    columnGap: "10px",
    marginBottom: "28px",
    color: "#a4a79f",
    fontSize: "10px",
    fontWeight: 700,
    letterSpacing: "0.18em",
    textTransform: "uppercase",
  },
  kickerDot: {
    width: "6px",
    height: "6px",
    borderRadius: "50%",
    backgroundColor: "#dfff45",
    boxShadow: "0 0 13px #dfff45",
  },
  heading: {
    margin: 0,
    fontSize: {
      default: "clamp(54px, 5.2vw, 86px)",
      [mobile]: "50px",
    },
    fontWeight: 510,
    letterSpacing: "-0.072em",
    lineHeight: 0.98,
  },
  headingEmphasis: {
    color: "#a9aa9f",
    fontFamily: "ui-serif, Georgia, serif",
    fontWeight: 400,
  },
  intro: {
    maxWidth: "500px",
    marginTop: "28px",
    marginRight: "0",
    marginBottom: "36px",
    marginLeft: "0",
    color: "#aeb1aa",
    fontSize: {
      default: "17px",
      [mobile]: "15px",
    },
    lineHeight: 1.55,
  },
  actions: {
    display: "flex",
    alignItems: {
      default: "center",
      [mobile]: "flex-start",
    },
    flexDirection: {
      [mobile]: "column",
    },
    rowGap: "25px",
    columnGap: "25px",
  },
  primaryButton: {
    display: "inline-flex",
    alignItems: "center",
    rowGap: "26px",
    columnGap: "26px",
    minHeight: "54px",
    borderWidth: 0,
    borderRadius: "2px",
    paddingTop: "0",
    paddingRight: "18px",
    paddingBottom: "0",
    paddingLeft: "22px",
    backgroundColor: "#dfff45",
    color: "#11120f",
    font: "inherit",
    fontSize: "13px",
    fontWeight: 780,
    textDecoration: "none",
  },
  textButton: {
    borderWidth: 0,
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: "#4d504b",
    paddingBlock: "6px",
    paddingInline: "0",
    backgroundColor: "transparent",
    color: "#e3e4df",
    cursor: "pointer",
    font: "inherit",
    fontSize: "12px",
    fontWeight: 650,
  },
  textButtonTime: {
    marginLeft: "8px",
    color: "#73766f",
    fontSize: "9px",
  },
  proof: {
    display: "flex",
    alignItems: "center",
    rowGap: "14px",
    columnGap: "14px",
    marginTop: {
      default: "42px",
      [mobile]: "30px",
    },
    color: "#777b74",
    fontSize: "10px",
  },
  avatarStack: {
    display: "flex",
  },
  proofAvatar: {
    display: "grid",
    width: "28px",
    height: "28px",
    marginLeft: "-6px",
    placeItems: "center",
    borderWidth: "2px",
    borderStyle: "solid",
    borderColor: "#101210",
    borderRadius: "50%",
    backgroundColor: "#393b37",
    color: "#d8d9d3",
    fontSize: "8px",
    fontStyle: "normal",
    fontWeight: 800,
  },
  firstProofAvatar: {
    marginLeft: 0,
    backgroundColor: "#f78061",
    color: "#23120d",
  },
  secondProofAvatar: {
    backgroundColor: "#7987ff",
    color: "#11152e",
  },
  thirdProofAvatar: {
    backgroundColor: "#dfff45",
    color: "#182000",
  },
  orbitScene: {
    position: "relative",
    height: {
      default: "min(680px, 70vw)",
      [tablet]: "550px",
      [mobile]: "500px",
    },
    minHeight: {
      default: "590px",
      [tablet]: 0,
    },
    marginTop: {
      [tablet]: "20px",
    },
    marginInline: {
      [mobile]: "-40px",
    },
    transform: {
      [mobile]: "scale(0.78)",
    },
  },
  orbitGlow: {
    position: "absolute",
    top: "50%",
    left: "51%",
    width: "320px",
    height: "320px",
    borderRadius: "50%",
    backgroundColor: "rgba(117, 92, 255, 0.15)",
    filter: "blur(70px)",
    transform: "translate(-50%, -50%)",
  },
  orbitRing: {
    position: "absolute",
    top: "50%",
    left: "51%",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "rgba(255, 255, 255, 0.09)",
    borderRadius: "50%",
    transform: "translate(-50%, -50%) rotate(-12deg)",
    "::after": {
      position: "absolute",
      top: "50%",
      left: "-3px",
      width: "5px",
      height: "5px",
      borderRadius: "50%",
      backgroundColor: "#dfff45",
      boxShadow: "0 0 12px #dfff45",
      content: "''",
    },
  },
  ringOne: {
    width: "310px",
    height: "235px",
  },
  ringTwo: {
    width: "520px",
    height: "390px",
    transform: "translate(-50%, -50%) rotate(19deg)",
  },
  ringThree: {
    width: {
      default: "710px",
      [tablet]: "620px",
    },
    height: {
      default: "530px",
      [tablet]: "450px",
    },
    transform: "translate(-50%, -50%) rotate(-8deg)",
  },
  coreCard: {
    position: "absolute",
    zIndex: 3,
    top: "50%",
    left: "51%",
    width: "220px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "rgba(255, 255, 255, 0.18)",
    borderRadius: "18px",
    padding: "18px",
    backgroundColor: "#171916",
    backgroundImage: "linear-gradient(145deg, #282b26, #171916)",
    boxShadow: "0 22px 70px rgba(0, 0, 0, 0.45)",
    transform: "translate(-50%, -50%)",
    animationName: {
      [motion]: float,
    },
    animationDuration: {
      [motion]: "5s",
    },
    animationTimingFunction: {
      [motion]: "ease-in-out",
    },
    animationIterationCount: {
      [motion]: "infinite",
    },
  },
  coreTop: {
    display: "flex",
    alignItems: "center",
    rowGap: "7px",
    columnGap: "7px",
    color: "#858980",
    fontSize: "8px",
    letterSpacing: "0.1em",
    textTransform: "uppercase",
  },
  coreIcon: {
    display: "grid",
    width: "24px",
    height: "24px",
    placeItems: "center",
    borderRadius: "7px",
    backgroundColor: "#dfff45",
    color: "#1b2105",
    fontWeight: 900,
  },
  liveDot: {
    width: "5px",
    height: "5px",
    marginLeft: "auto",
    borderRadius: "50%",
    backgroundColor: "#6feb8d",
  },
  coreTitle: {
    display: "block",
    marginTop: "18px",
    fontSize: "22px",
    letterSpacing: "-0.04em",
  },
  coreMeta: {
    color: "#7d817a",
    fontSize: "9px",
  },
  coreBars: {
    display: "flex",
    alignItems: "end",
    rowGap: "5px",
    columnGap: "5px",
    height: "35px",
    marginTop: "17px",
  },
  coreBar: {
    width: "22%",
    borderRadius: "2px",
    backgroundColor: "#474a44",
  },
  coreBarOne: { height: "40%" },
  coreBarTwo: { height: "80%", backgroundColor: "#7b69ef" },
  coreBarThree: { height: "62%" },
  coreBarFour: { height: "100%", backgroundColor: "#dfff45" },
  agentCard: {
    position: "absolute",
    zIndex: 4,
    display: "grid",
    gridTemplateColumns: "auto 1fr auto",
    alignItems: "center",
    rowGap: "10px",
    columnGap: "10px",
    width: {
      default: "245px",
      [mobile]: "220px",
    },
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "rgba(255, 255, 255, 0.12)",
    borderRadius: "12px",
    padding: "11px",
    backgroundColor: "rgba(27, 30, 26, 0.9)",
    boxShadow: "0 14px 35px rgba(0, 0, 0, 0.33)",
    backdropFilter: "blur(12px)",
  },
  agentOne: {
    top: "15%",
    left: "4%",
    transform: "rotate(-2deg)",
    animationName: { [motion]: driftOne },
    animationDuration: { [motion]: "6s" },
    animationTimingFunction: { [motion]: "ease-in-out" },
    animationIterationCount: { [motion]: "infinite" },
  },
  agentTwo: {
    right: "-2%",
    bottom: "21%",
    transform: "rotate(2deg)",
    animationName: { [motion]: driftTwo },
    animationDuration: { [motion]: "7s" },
    animationTimingFunction: { [motion]: "ease-in-out" },
    animationIterationCount: { [motion]: "infinite" },
  },
  agentThree: {
    bottom: "7%",
    left: "10%",
    transform: "rotate(-1deg)",
  },
  agentAvatar: {
    display: "grid",
    width: "34px",
    height: "34px",
    placeItems: "center",
    borderRadius: "9px",
    color: "#141512",
    fontSize: "11px",
    fontWeight: 900,
  },
  coral: { backgroundColor: "#f77d61" },
  blue: { backgroundColor: "#7788ff" },
  lime: { backgroundColor: "#dfff45" },
  agentTitle: {
    display: "block",
    fontSize: "10px",
  },
  agentMeta: {
    display: "block",
    marginTop: "2px",
    color: "#777b73",
    fontSize: "8px",
  },
  status: {
    borderRadius: "10px",
    paddingBlock: "4px",
    paddingInline: "6px",
    fontSize: "7px",
    fontWeight: 800,
  },
  working: {
    backgroundColor: "rgba(111, 235, 141, 0.12)",
    color: "#84eda0",
  },
  waiting: {
    backgroundColor: "rgba(255, 190, 77, 0.12)",
    color: "#ffc76b",
  },
  signalPing: {
    position: "absolute",
    width: "9px",
    height: "9px",
    borderWidth: "2px",
    borderStyle: "solid",
    borderColor: "#101210",
    borderRadius: "50%",
    backgroundColor: "#dfff45",
    boxShadow: "0 0 0 6px rgba(223, 255, 69, 0.08)",
  },
  pingOne: {
    top: "27%",
    right: "11%",
  },
  pingTwo: {
    bottom: "31%",
    left: "8%",
    backgroundColor: "#7b69ef",
    boxShadow: "0 0 0 6px rgba(123, 105, 239, 0.1)",
  },
  signalStrip: {
    position: {
      default: "absolute",
      [tablet]: "relative",
    },
    bottom: 0,
    left: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: {
      default: "center",
      [mobile]: "flex-start",
    },
    flexWrap: {
      [mobile]: "wrap",
    },
    gap: {
      default: "30px",
      [mobile]: "10px 18px",
    },
    width: "100%",
    height: {
      default: "50px",
      [mobile]: "auto",
    },
    padding: {
      [mobile]: "14px 90px 80px 18px",
    },
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: "rgba(255, 255, 255, 0.1)",
    color: "#73766f",
    fontSize: "9px",
    letterSpacing: "0.08em",
    textTransform: "uppercase",
  },
  stripDot: {
    width: "3px",
    height: "3px",
    borderRadius: "50%",
    backgroundColor: "#444741",
  },
});
