import * as stylex from "@stylexjs/stylex";

const mobile = "@media (max-width: 760px)" as const;

export const search = stylex.create({
  main: {
    display: "flex",
    flexDirection: "column",
    minWidth: 0,
    minHeight: "100vh",
    paddingBottom: { default: "50px", [mobile]: "110px" },
    backgroundColor: "#111310",
  },
  content: {
    width: "min(820px, calc(100% - 40px))",
    marginInline: "auto",
    paddingTop: { default: "36px", [mobile]: "20px" },
    paddingBottom: "40px",
  },
  intro: {
    maxWidth: "620px",
    marginBottom: "22px",
  },
  eyebrow: {
    color: "#777b73",
    fontSize: "10px",
    fontWeight: 850,
    letterSpacing: "0.15em",
  },
  heading: {
    marginBlockStart: "9px",
    marginBlockEnd: "0",
    color: "#f1f2ed",
    fontSize: { default: "38px", [mobile]: "31px" },
    fontWeight: 650,
    letterSpacing: "-0.055em",
  },
  lede: {
    marginBlockStart: "13px",
    marginBlockEnd: "0",
    color: "#8e9289",
    fontSize: "14px",
    lineHeight: 1.6,
  },
  form: {
    marginBottom: "22px",
  },
  field: {
    display: "flex",
    alignItems: "center",
    rowGap: "10px",
    columnGap: "10px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "#343831",
    borderRadius: "12px",
    paddingInline: "14px",
    backgroundColor: "#171a16",
  },
  fieldIcon: {
    width: "16px",
    color: "#73776f",
    flexShrink: 0,
  },
  input: {
    flexGrow: "1",
    flexShrink: "1",
    flexBasis: "0%",
    minWidth: 0,
    height: "48px",
    borderWidth: 0,
    backgroundColor: "transparent",
    color: "#eef0e9",
    font: "inherit",
    fontSize: "15px",
    outline: "none",
  },
  submit: {
    height: "34px",
    borderWidth: 0,
    borderRadius: "8px",
    paddingInline: "14px",
    backgroundColor: "#dfff45",
    color: "#182000",
    font: "inherit",
    fontSize: "13px",
    fontWeight: 750,
    cursor: { default: "pointer", ":disabled": "not-allowed" },
    opacity: { default: 1, ":disabled": 0.45 },
  },
  clear: {
    height: "28px",
    borderWidth: 0,
    borderRadius: "7px",
    paddingInline: "8px",
    backgroundColor: "transparent",
    color: "#8e9289",
    font: "inherit",
    fontSize: "12px",
    fontWeight: 700,
    cursor: "pointer",
  },
  error: {
    marginBottom: "16px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "#5a2f2a",
    borderRadius: "10px",
    paddingBlock: "12px",
    paddingInline: "14px",
    backgroundColor: "#241614",
    color: "#f0b4aa",
    fontSize: "13px",
  },
  empty: {
    color: "#7d8178",
    fontSize: "14px",
    lineHeight: 1.5,
  },
  section: {
    marginBottom: "22px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "#343831",
    borderRadius: "14px",
    padding: { default: "18px 20px", [mobile]: "16px" },
    backgroundColor: "#171a16",
  },
  sectionHeading: {
    display: "flex",
    alignItems: "baseline",
    justifyContent: "space-between",
    rowGap: "12px",
    columnGap: "12px",
    marginBottom: "14px",
  },
  sectionTitle: {
    margin: 0,
    color: "#f1f2ed",
    fontSize: "15px",
    fontWeight: 700,
    letterSpacing: "-0.02em",
  },
  sectionCount: {
    color: "#777b73",
    fontSize: "12px",
    fontWeight: 750,
  },
  list: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    display: "grid",
    rowGap: "8px",
    columnGap: "8px",
  },
  result: {
    display: "block",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: { default: "#2c2f2a", ":hover": "#43473f" },
    borderRadius: "11px",
    paddingBlock: "12px",
    paddingInline: "14px",
    backgroundColor: { default: "#141714", ":hover": "#1b1e19" },
    color: "inherit",
    textDecoration: "none",
    outline: "none",
  },
  resultActive: {
    borderColor: "#dfff45",
    boxShadow: "0 0 0 1px rgba(223, 255, 69, 0.25)",
    backgroundColor: "#1b1e19",
  },
  resultTitle: {
    display: "block",
    color: "#f2f3ed",
    fontSize: "14px",
    fontWeight: 700,
    letterSpacing: "-0.01em",
  },
  resultMeta: {
    display: "block",
    marginTop: "4px",
    color: "#7d8178",
    fontSize: "12px",
  },
  resultBody: {
    display: "block",
    marginTop: "8px",
    color: "#b7bbb2",
    fontSize: "13px",
    lineHeight: 1.5,
    whiteSpace: "pre-wrap",
  },
  resultExtra: {
    display: "block",
    marginTop: "6px",
    color: "#8e9289",
    fontSize: "12px",
    lineHeight: 1.45,
    whiteSpace: "pre-wrap",
  },
  resultLinks: {
    display: "flex",
    flexWrap: "wrap",
    rowGap: "8px",
    columnGap: "8px",
    marginTop: "8px",
  },
  resultLink: {
    color: "#c8d98a",
    fontSize: "12px",
  },
  status: {
    position: "absolute",
    width: "1px",
    height: "1px",
    overflow: "hidden",
    clip: "rect(0, 0, 0, 0)",
    whiteSpace: "nowrap",
  },
});
