import * as stylex from "@stylexjs/stylex";

const mobile = "@media (max-width: 760px)" as const;

export const settings = stylex.create({
  main: {
    minWidth: 0,
    minHeight: "100vh",
    paddingBottom: { default: "50px", [mobile]: "110px" },
    backgroundColor: "#111310",
  },
  topbar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    height: { default: "78px", [mobile]: "66px" },
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: "#2a2d28",
    paddingInline: { default: "28px", [mobile]: "15px" },
  },
  topbarLabel: {
    display: "block",
    marginBottom: "4px",
    color: "#656960",
    fontSize: "10px",
    fontWeight: 800,
    letterSpacing: "0.15em",
  },
  topbarTitle: {
    display: "block",
    color: "#eef0e9",
    fontSize: { default: "24px", [mobile]: "21px" },
    letterSpacing: "-0.025em",
  },
  backLink: {
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: "#555950",
    color: "#a8aca3",
    fontSize: "12px",
    fontWeight: 700,
    textDecoration: "none",
  },
  content: {
    width: "min(760px, calc(100% - 40px))",
    marginInline: "auto",
    paddingTop: { default: "48px", [mobile]: "24px" },
  },
  intro: {
    maxWidth: "590px",
    marginBottom: "26px",
  },
  preferenceIntro: { marginTop: "42px" },
  preferenceHeading: {
    marginBlockStart: "9px",
    marginBlockEnd: "0",
    color: "#f1f2ed",
    fontSize: { default: "27px", [mobile]: "24px" },
    fontWeight: 650,
    letterSpacing: "-0.04em",
  },
  eyebrow: {
    color: "#777b73",
    fontSize: "10px",
    fontWeight: 850,
    letterSpacing: "0.15em",
  },
  heading: {
    marginBlockStart: "9px",
    marginBlockEnd: "0",
    color: "#f1f2ed",
    fontSize: { default: "38px", [mobile]: "31px" },
    fontWeight: 650,
    letterSpacing: "-0.055em",
  },
  lede: {
    marginBlockStart: "13px",
    marginBlockEnd: "0",
    color: "#8e9289",
    fontSize: "14px",
    lineHeight: 1.6,
  },
  card: {
    display: "grid",
    gridTemplateColumns: { default: "150px 1fr", [mobile]: "1fr" },
    gap: { default: "28px", [mobile]: "20px" },
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "#343831",
    borderRadius: "15px",
    padding: { default: "26px", [mobile]: "20px" },
    backgroundColor: "#171a16",
  },
  preferenceCard: { display: "block" },
  preview: {
    display: "flex",
    alignItems: "center",
    flexDirection: "column",
    justifyContent: "center",
    minHeight: "160px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "#30342e",
    borderRadius: "12px",
    backgroundColor: "#121411",
  },
  avatar: {
    display: "grid",
    width: "62px",
    height: "62px",
    placeItems: "center",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "#555a50",
    borderRadius: "50%",
    backgroundColor: "#292d27",
    color: "#dfff45",
    fontSize: "18px",
    fontWeight: 850,
  },
  previewName: {
    marginTop: "12px",
    color: "#d9dbd4",
    fontSize: "13px",
    fontWeight: 750,
    textAlign: "center",
  },
  form: {
    display: "flex",
    flexDirection: "column",
  },
  label: {
    color: "#777b73",
    fontSize: "10px",
    fontWeight: 850,
    letterSpacing: "0.13em",
  },
  checkboxLabel: {
    display: "flex",
    alignItems: "center",
    columnGap: "10px",
    marginTop: "4px",
    color: "#b7bbb2",
    fontSize: "13px",
    fontWeight: 600,
    letterSpacing: "0.01em",
    cursor: "pointer",
  },
  input: {
    width: "100%",
    height: "48px",
    marginTop: "9px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: { default: "#3b3f38", ":focus": "#dfff45" },
    borderRadius: "8px",
    paddingInline: "13px",
    outline: "none",
    backgroundColor: "#101210",
    color: "#f0f1eb",
    font: "inherit",
    fontSize: "15px",
    boxShadow: { default: "none", ":focus": "0 0 0 3px rgba(223, 255, 69, 0.08)" },
  },
  hint: {
    marginBlockStart: "9px",
    marginBlockEnd: "0",
    color: "#6e726a",
    fontSize: "11px",
    lineHeight: 1.5,
  },
  error: {
    marginBlockStart: "12px",
    marginBlockEnd: "0",
    color: "#ff9a8b",
    fontSize: "12px",
  },
  actions: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap",
    rowGap: "12px",
    columnGap: "12px",
    marginTop: "27px",
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: "#30332e",
    paddingTop: "18px",
  },
  actionsEnd: {
    display: "flex",
    alignItems: "center",
    rowGap: "12px",
    columnGap: "12px",
  },
  saved: {
    color: "#82e99a",
    fontSize: "11px",
    fontWeight: 750,
  },
  saveButton: {
    height: "41px",
    borderWidth: 0,
    borderRadius: "8px",
    paddingInline: "17px",
    backgroundColor: "#dfff45",
    color: "#182000",
    font: "inherit",
    fontSize: "13px",
    fontWeight: 850,
    cursor: { default: "pointer", ":disabled": "not-allowed" },
    opacity: { default: 1, ":disabled": 0.4 },
  },
  note: {
    display: "flex",
    rowGap: "10px",
    columnGap: "10px",
    marginTop: "16px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "rgba(223, 255, 69, 0.16)",
    borderRadius: "10px",
    padding: "13px",
    backgroundColor: "rgba(223, 255, 69, 0.035)",
    color: "#858980",
    fontSize: "11px",
    lineHeight: 1.5,
  },
  noteMark: {
    color: "#dfff45",
    fontWeight: 900,
  },
  instanceList: {
    display: "flex",
    flexDirection: "column",
    rowGap: "14px",
  },
  instanceCard: {
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "#30342e",
    borderRadius: "10px",
    padding: "16px",
    backgroundColor: "#121411",
  },
  instanceHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: "12px",
  },
  instanceTitle: {
    color: "#d9dbd4",
    fontSize: "12px",
    fontWeight: 800,
    letterSpacing: "0.08em",
  },
  fieldStack: {
    display: "flex",
    flexDirection: "column",
    rowGap: "12px",
  },
  secondaryButton: {
    height: "41px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "#4a4f46",
    borderRadius: "8px",
    paddingInline: "15px",
    backgroundColor: "transparent",
    color: "#d7dbd0",
    font: "inherit",
    fontSize: "13px",
    fontWeight: 750,
    cursor: { default: "pointer", ":disabled": "not-allowed" },
    opacity: { default: 1, ":disabled": 0.4 },
  },
  removeButton: {
    height: "32px",
    borderWidth: 0,
    borderRadius: "6px",
    paddingInline: "10px",
    backgroundColor: "transparent",
    color: "#b7bdb2",
    font: "inherit",
    fontSize: "12px",
    fontWeight: 700,
    cursor: { default: "pointer", ":disabled": "not-allowed" },
    opacity: { default: 1, ":disabled": 0.4 },
    textDecoration: { default: "none", ":hover": "underline" },
  },
  emptyState: {
    marginBlockStart: "0",
    marginBlockEnd: "0",
    color: "#6e726a",
    fontSize: "12px",
    lineHeight: 1.5,
  },
});
