import * as stylex from "@stylexjs/stylex";

export const quickSearch = stylex.create({
  backdrop: {
    position: "fixed",
    inset: 0,
    zIndex: 10000,
    display: "grid",
    alignItems: "start",
    justifyItems: "center",
    paddingTop: "12vh",
    paddingInline: "16px",
    backgroundColor: "rgba(8, 10, 8, 0.72)",
  },
  dialog: {
    width: "min(560px, 100%)",
    maxHeight: "min(70vh, 520px)",
    display: "flex",
    flexDirection: "column",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "#353932",
    borderRadius: "14px",
    backgroundColor: "#171a16",
    color: "#e8ebe4",
    boxShadow: "0 24px 60px rgba(0, 0, 0, 0.45)",
    overflow: "hidden",
  },
  closeButton: {
    borderWidth: 0,
    borderRadius: "8px",
    paddingBlock: "6px",
    paddingInline: "10px",
    backgroundColor: { default: "transparent", ":hover": "#2a2d28" },
    color: "#aeb2a8",
    font: "inherit",
    fontSize: "13px",
    cursor: "pointer",
  },
  inputRow: {
    display: "grid",
    gridTemplateColumns: "20px 1fr auto",
    alignItems: "center",
    columnGap: "10px",
    paddingBlock: "14px",
    paddingInline: "14px",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: "#2a2d28",
  },
  input: {
    borderWidth: 0,
    backgroundColor: "transparent",
    color: "#f2f5ee",
    font: "inherit",
    fontSize: "16px",
    outline: "none",
  },
  status: {
    paddingBlock: "8px",
    paddingInline: "14px",
    color: "#8b9087",
    fontSize: "12px",
  },
  error: {
    color: "#f5a89a",
  },
  list: {
    overflow: "auto",
    scrollbarColor: "#4a5046 transparent",
    scrollbarWidth: "thin",
    paddingBlock: "6px",
    paddingInline: "6px",
    margin: 0,
    listStyle: "none",
  },
  groupLabel: {
    paddingBlock: "8px",
    paddingInline: "10px",
    color: "#6f746c",
    fontSize: "11px",
    letterSpacing: "0.04em",
    textTransform: "uppercase",
  },
  option: {
    display: "grid",
    gridTemplateColumns: "32px minmax(0, 1fr) auto",
    alignItems: "center",
    columnGap: "12px",
    width: "100%",
    borderWidth: 0,
    borderRadius: "10px",
    paddingBlock: "10px",
    paddingInline: "10px",
    backgroundColor: { default: "transparent", ":hover": "#22251f" },
    color: "inherit",
    font: "inherit",
    textAlign: "left",
    cursor: "pointer",
  },
  optionActive: {
    backgroundColor: "#2a2f28",
  },
  entityIcon: {
    display: "grid",
    width: "32px",
    height: "32px",
    flexShrink: 0,
    placeItems: "center",
    borderRadius: "9px",
    color: "#c7cbc1",
  },
  entityIconSession: {
    backgroundColor: "#243028",
    color: "#b7e0c8",
  },
  entityIconSpace: {
    backgroundColor: "#2a2820",
    color: "#e6d3a0",
  },
  entityIconAction: {
    backgroundColor: "#1f2830",
    color: "#a8c4d8",
  },
  entityIconSvg: {
    width: "20px",
    height: "20px",
    fill: "none",
    stroke: "currentColor",
    strokeLinecap: "round",
    strokeLinejoin: "round",
    strokeWidth: 1.85,
  },
  optionBody: {
    minWidth: 0,
    display: "grid",
    rowGap: "2px",
  },
  optionTitle: {
    overflow: "hidden",
    fontSize: "14px",
    fontWeight: 600,
    color: "#f2f5ee",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  optionMeta: {
    overflow: "hidden",
    fontSize: "12px",
    color: "#8b9087",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  matchMark: {
    borderRadius: "3px",
    backgroundColor: "rgba(214, 196, 120, 0.22)",
    color: "#f2e6b8",
    fontWeight: 700,
  },
  badges: {
    display: "flex",
    flexShrink: 0,
    flexDirection: "column",
    alignItems: "flex-end",
    rowGap: "4px",
  },
  badge: {
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "#4a4030",
    borderRadius: "999px",
    paddingBlock: "2px",
    paddingInline: "8px",
    color: "#e6c48a",
    fontSize: "11px",
    whiteSpace: "nowrap",
  },
  idBadge: {
    borderColor: "#3a4540",
    color: "#a8c4b6",
  },
  empty: {
    paddingBlock: "24px",
    paddingInline: "14px",
    color: "#8b9087",
    fontSize: "14px",
    textAlign: "center",
  },
  visuallyHidden: {
    position: "absolute",
    width: "1px",
    height: "1px",
    padding: 0,
    margin: "-1px",
    overflow: "hidden",
    clip: "rect(0, 0, 0, 0)",
    whiteSpace: "nowrap",
    borderWidth: 0,
  },
});
