import * as stylex from "@stylexjs/stylex";

const mobile = "@media (max-width: 760px)" as const;

export const bell = stylex.create({
  wrap: { position: "relative" },
  trigger: {
    position: "relative",
    display: "grid",
    width: { default: "38px", [mobile]: "34px" },
    height: { default: "38px", [mobile]: "34px" },
    placeItems: "center",
    borderWidth: 0,
    borderRadius: "10px",
    backgroundColor: { default: "transparent", ":hover": "#282b26" },
    color: { default: "#73776f", ":hover": "#f2f3ed" },
    cursor: "pointer",
  },
  triggerOpen: { backgroundColor: "#282b26", color: "#f2f3ed" },
  badge: {
    position: "absolute",
    top: "2px",
    right: "1px",
    display: "grid",
    minWidth: "17px",
    height: "17px",
    placeItems: "center",
    borderWidth: "2px",
    borderStyle: "solid",
    borderColor: "#0c0e0c",
    borderRadius: "9px",
    paddingInline: "3px",
    backgroundColor: "#fa795f",
    color: "#190b08",
    fontSize: "9px",
    fontWeight: 900,
    lineHeight: 1,
  },
  panel: {
    position: "fixed",
    zIndex: 120,
    top: { default: "138px", [mobile]: "auto" },
    right: { default: "auto", [mobile]: "10px" },
    bottom: { default: "auto", [mobile]: "72px" },
    left: { default: "78px", [mobile]: "10px" },
    display: "flex",
    flexDirection: "column",
    width: { default: "410px", [mobile]: "auto" },
    maxHeight: { default: "calc(100vh - 164px)", [mobile]: "calc(100dvh - 92px)" },
    overflow: "hidden",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "#3a3e37",
    borderRadius: "16px",
    backgroundColor: "#141713",
    boxShadow: "0 24px 70px rgba(0, 0, 0, 0.62)",
    color: "#eff1ea",
  },
  panelTopbar: {
    top: { default: "64px", [mobile]: "auto" },
    right: { default: "18px", [mobile]: "10px" },
    left: { default: "auto", [mobile]: "10px" },
    bottom: { default: "auto", [mobile]: "72px" },
  },
  header: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: "#2b2f29",
    paddingTop: "18px",
    paddingRight: "18px",
    paddingBottom: "14px",
    paddingLeft: "18px",
  },
  eyebrow: {
    display: "block",
    marginBottom: "5px",
    color: "#73786e",
    fontSize: "9px",
    fontWeight: 900,
    letterSpacing: "0.17em",
  },
  title: { display: "block", fontSize: "19px", letterSpacing: "-0.02em" },
  close: {
    display: "grid",
    width: "30px",
    height: "30px",
    placeItems: "center",
    borderWidth: 0,
    borderRadius: "8px",
    backgroundColor: { default: "transparent", ":hover": "#282c26" },
    color: "#8d9288",
    font: "inherit",
    fontSize: "20px",
    cursor: "pointer",
  },
  scroll: {
    flexGrow: 1,
    overflowY: "auto",
    paddingTop: "12px",
    paddingRight: "14px",
    paddingBottom: "16px",
    paddingLeft: "14px",
    scrollbarColor: "#4a5046 transparent",
    scrollbarWidth: "thin",
  },
  sectionHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: "2px",
    marginBottom: "8px",
  },
  sectionLabel: {
    color: "#72776d",
    fontSize: "9px",
    fontWeight: 900,
    letterSpacing: "0.15em",
  },
  liveCard: {
    display: "grid",
    gridTemplateColumns: "10px 1fr auto",
    rowGap: "10px",
    columnGap: "10px",
    alignItems: "start",
    marginBottom: "12px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "#343a2d",
    borderRadius: "11px",
    padding: "12px",
    backgroundColor: "#1a1e17",
  },
  stateDot: {
    width: "8px",
    height: "8px",
    marginTop: "4px",
    borderRadius: "50%",
    backgroundColor: "#dfff45",
    boxShadow: "0 0 0 4px rgba(223, 255, 69, 0.1)",
  },
  cardText: { minWidth: 0 },
  cardTitle: {
    display: "block",
    overflow: "hidden",
    color: "#eff1ea",
    fontSize: "12px",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  cardDetail: {
    display: "block",
    overflow: "hidden",
    marginTop: "3px",
    color: "#858b80",
    fontSize: "10px",
    lineHeight: 1.35,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  inboxCard: {
    position: "relative",
    display: "grid",
    gridTemplateColumns: "10px 1fr auto",
    rowGap: "10px",
    columnGap: "10px",
    marginBottom: "5px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "transparent",
    borderRadius: "11px",
    padding: "11px",
    backgroundColor: "#1a1d18",
  },
  eventGlyph: {
    display: "grid",
    width: "18px",
    height: "18px",
    placeItems: "center",
    borderRadius: "6px",
    backgroundColor: "#2b3028",
    color: "#c7cebf",
    fontSize: "10px",
    fontWeight: 900,
  },
  eventMeta: {
    display: "flex",
    flexWrap: "wrap",
    rowGap: "6px",
    columnGap: "6px",
    marginTop: "5px",
    color: "#6d7369",
    fontSize: "9px",
  },
  eventTime: { color: "#697066", fontSize: "9px", whiteSpace: "nowrap" },
  eventLink: {
    color: "inherit",
    textDecoration: "none",
  },
  dismiss: {
    position: "absolute",
    top: "6px",
    right: "6px",
    display: "grid",
    width: "22px",
    height: "22px",
    placeItems: "center",
    borderWidth: 0,
    borderRadius: "6px",
    backgroundColor: { default: "transparent", ":hover": "#2c3029" },
    color: "#8a9086",
    font: "inherit",
    fontSize: "14px",
    cursor: "pointer",
  },
  empty: {
    marginBlock: "18px",
    marginInline: "4px",
    color: "#7a8076",
    fontSize: "12px",
    lineHeight: 1.4,
  },
  error: {
    marginBlock: "12px",
    marginInline: "4px",
    color: "#f0a090",
    fontSize: "11px",
    lineHeight: 1.4,
  },
  footer: {
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: "#2b2f29",
    paddingBlock: "12px",
    paddingInline: "14px",
    backgroundColor: "#10130f",
  },
  tabs: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    rowGap: "4px",
    columnGap: "4px",
    borderRadius: "10px",
    padding: "4px",
    backgroundColor: "#0d0f0d",
  },
  tab: {
    borderWidth: 0,
    borderRadius: "7px",
    paddingBlock: "8px",
    paddingInline: "10px",
    backgroundColor: "transparent",
    color: "#777c72",
    font: "inherit",
    fontSize: "11px",
    fontWeight: 800,
    cursor: "pointer",
  },
  tabActive: { backgroundColor: "#282c26", color: "#f2f4ec" },
  tabDisabled: { opacity: 0.45, cursor: "not-allowed" },
  tabCount: {
    marginLeft: "5px",
    borderRadius: "9px",
    paddingBlock: "1px",
    paddingInline: "5px",
    backgroundColor: "#383d35",
    color: "#bdc2b7",
    fontSize: "9px",
  },
  tabCountActive: { backgroundColor: "#dfff45", color: "#172000" },
});
