import * as stylex from "@stylexjs/stylex";

const mobile = "@media (max-width: 760px)" as const;

export const roster = stylex.create({
  section: {
    marginTop: "8px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "#30342e",
    borderRadius: "15px",
    backgroundColor: "#151814",
    overflow: "hidden",
  },
  header: {
    display: "flex",
    flexDirection: { default: "row", [mobile]: "column" },
    alignItems: { default: "center", [mobile]: "flex-start" },
    justifyContent: "space-between",
    rowGap: "12px",
    columnGap: "12px",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: "#2b2f29",
    padding: { default: "14px 16px", [mobile]: "14px" },
  },
  eyebrow: {
    display: "block",
    marginBottom: "4px",
    color: "#71766d",
    fontSize: "9px",
    fontWeight: 900,
    letterSpacing: "0.16em",
  },
  title: {
    display: "block",
    color: "#f0f2eb",
    fontSize: { default: "16px", [mobile]: "15px" },
    letterSpacing: "-0.02em",
  },
  subtitle: {
    display: "block",
    marginTop: "3px",
    color: "#72786e",
    fontSize: "10px",
  },
  summary: {
    display: "flex",
    flexWrap: "wrap",
    rowGap: "6px",
    columnGap: "6px",
  },
  summaryPill: {
    display: "inline-flex",
    alignItems: "center",
    rowGap: "6px",
    columnGap: "6px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "#343930",
    borderRadius: "11px",
    paddingBlock: "5px",
    paddingInline: "8px",
    backgroundColor: "#1b1f19",
    color: "#aeb4a8",
    fontSize: "10px",
    fontWeight: 750,
    whiteSpace: "nowrap",
  },
  summaryDot: {
    width: "8px",
    height: "8px",
    borderRadius: "50%",
    backgroundColor: "#dfff45",
  },
  summaryDotError: { backgroundColor: "#fa795f" },
  summaryDotAttention: { backgroundColor: "#e6b75f" },
  summaryDotIdle: { backgroundColor: "#91bdd7" },
  list: { margin: 0, padding: 0, listStyle: "none" },
  item: {
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: "#292d27",
  },
  row: {
    display: "grid",
    gridTemplateColumns: {
      default: "minmax(160px, 0.9fr) auto minmax(200px, 1.2fr) auto 36px",
      [mobile]: "minmax(0, 1fr) auto auto 36px",
    },
    alignItems: "center",
    gap: { default: "12px", [mobile]: "8px" },
    width: "100%",
    padding: { default: "12px 14px", [mobile]: "12px" },
  },
  open: {
    display: "grid",
    rowGap: "2px",
    columnGap: "2px",
    minWidth: 0,
    borderWidth: 0,
    padding: 0,
    backgroundColor: "transparent",
    color: "inherit",
    font: "inherit",
    textAlign: "left",
    textDecoration: "none",
    cursor: "pointer",
  },
  badges: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "flex-end",
    rowGap: "4px",
    columnGap: "4px",
    minWidth: 0,
  },
  state: {
    display: "inline-flex",
    alignItems: "center",
    rowGap: "5px",
    columnGap: "5px",
    maxWidth: "100%",
    marginBottom: "2px",
    overflow: "hidden",
    color: "#8ce39a",
    fontSize: "8px",
    fontWeight: 900,
    letterSpacing: "0.1em",
    textOverflow: "ellipsis",
    textTransform: "none",
    whiteSpace: "nowrap",
  },
  stateLabel: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  stateError: { color: "#ff927a" },
  stateAttention: { color: "#e6b75f" },
  stateIdle: { color: "#91bdd7" },
  stateUnknown: { color: "#8a9086" },
  stateDot: {
    width: "6px",
    height: "6px",
    borderRadius: "50%",
    backgroundColor: "currentColor",
  },
  name: {
    display: "block",
    overflow: "hidden",
    color: "#eff1ea",
    fontSize: "13px",
    fontWeight: 700,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  meta: {
    display: "block",
    overflow: "hidden",
    marginTop: "2px",
    color: "#666c63",
    fontSize: "10px",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  latest: {
    minWidth: 0,
    display: { default: "block", [mobile]: "none" },
  },
  latestLabel: {
    display: "block",
    marginBottom: "3px",
    color: "#62685f",
    fontSize: "8px",
    fontWeight: 900,
    letterSpacing: "0.1em",
  },
  latestText: {
    display: "block",
    overflow: "hidden",
    color: "#aeb4aa",
    fontSize: "11px",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  latestEmpty: { color: "#5f6560", fontStyle: "italic" },
  time: {
    color: "#666c63",
    fontSize: "10px",
    whiteSpace: "nowrap",
    justifySelf: { default: "end", [mobile]: "end" },
  },
  expand: {
    display: "grid",
    width: "32px",
    height: "32px",
    placeItems: "center",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "#343930",
    borderRadius: "9px",
    backgroundColor: { default: "#1b1f19", ":hover": "#242922" },
    color: "#aeb4a8",
    cursor: "pointer",
  },
  expandOpen: {
    backgroundColor: "#292c27",
    color: "#d4d6cf",
  },
  chevron: {
    display: "inline-block",
    transform: "rotate(0deg)",
    transition: "transform 140ms ease",
  },
  chevronOpen: { transform: "rotate(90deg)" },
  mobileLatest: {
    display: { default: "none", [mobile]: "block" },
    gridColumnEnd: "-1",
    gridColumnStart: "1",
    overflow: "hidden",
    marginTop: "-4px",
    paddingInline: "14px",
    paddingBottom: "10px",
    color: "#8a9086",
    fontSize: "11px",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  details: {
    margin: { default: "0 14px 12px", [mobile]: "0 12px 12px" },
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "#30342e",
    borderRadius: "10px",
    backgroundColor: "#10130f",
    overflow: "hidden",
  },
  detailGrid: {
    display: "grid",
    gridTemplateColumns: { default: "1fr 1fr", [mobile]: "1fr" },
    rowGap: "1px",
    columnGap: "1px",
    backgroundColor: "#292d27",
  },
  detailBlock: {
    minWidth: 0,
    paddingBlock: "11px",
    paddingInline: "12px",
    backgroundColor: "#141713",
  },
  detailWide: {
    gridColumn: { default: "1 / -1", [mobile]: "auto" },
  },
  detailLabel: {
    display: "block",
    marginBottom: "5px",
    color: "#62685f",
    fontSize: "8px",
    fontWeight: 900,
    letterSpacing: "0.1em",
  },
  workspaceLink: {
    color: "#dfff45",
    fontSize: "12px",
    textDecoration: { default: "none", ":hover": "underline" },
    overflowWrap: "anywhere",
  },
  sessionLine: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    rowGap: "8px",
    columnGap: "8px",
  },
  sessionId: {
    overflowWrap: "anywhere",
    color: "#cfd3c8",
    fontSize: "11px",
  },
  sessionIdLink: {
    color: "inherit",
    textDecoration: "underline",
    textDecorationColor: "#4a5048",
    textUnderlineOffset: "2px",
  },
  copyButton: {
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "#3a4038",
    borderRadius: "8px",
    paddingBlock: "4px",
    paddingInline: "8px",
    backgroundColor: "#1b1f19",
    color: "#d4d6cf",
    fontSize: "10px",
    cursor: "pointer",
  },
  messageText: {
    color: "#c5cac0",
    fontSize: "12px",
    overflowWrap: "anywhere",
  },
  timerText: {
    color: "#c5cac0",
    fontSize: "12px",
  },
  muted: {
    color: "#6a7068",
    fontSize: "12px",
    fontStyle: "italic",
  },
  empty: {
    paddingBlock: "28px",
    paddingInline: "18px",
    textAlign: "center",
  },
  emptyTitle: {
    display: "block",
    color: "#e8ebe3",
    fontSize: "14px",
  },
  emptyBody: {
    display: "block",
    marginTop: "6px",
    color: "#72786e",
    fontSize: "12px",
  },
  footer: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    rowGap: "10px",
    columnGap: "10px",
    paddingBlock: "10px",
    paddingInline: "14px",
    color: "#6a7068",
    fontSize: "10px",
  },
  historyButton: {
    borderWidth: 0,
    paddingBlock: "4px",
    paddingInline: "0",
    backgroundColor: "transparent",
    color: "#a9b19f",
    font: "inherit",
    fontSize: "10px",
    fontWeight: 800,
    cursor: "pointer",
  },
  actions: {
    display: "flex",
    flexWrap: "wrap",
    rowGap: "8px",
    columnGap: "8px",
    marginTop: "12px",
    justifyContent: "center",
  },
});
