import * as stylex from "@stylexjs/stylex";

const mobile = "@media (max-width: 760px)" as const;

export const history = stylex.create({
  layer: { position: "fixed", zIndex: 180, inset: 0 },
  backdrop: {
    position: "absolute",
    inset: 0,
    borderWidth: 0,
    backgroundColor: "rgba(3, 5, 3, 0.72)",
    cursor: "default",
  },
  panel: {
    position: "absolute",
    zIndex: 1,
    top: { default: "12px", [mobile]: 0 },
    right: { default: "12px", [mobile]: 0 },
    bottom: { default: "12px", [mobile]: 0 },
    display: "flex",
    flexDirection: "column",
    width: { default: "min(540px, calc(100vw - 24px))", [mobile]: "100%" },
    borderWidth: { default: "1px", [mobile]: 0 },
    borderStyle: "solid",
    borderColor: "#3a3f37",
    borderRadius: { default: "16px", [mobile]: 0 },
    backgroundColor: "#141713",
    boxShadow: "-24px 0 70px rgba(0, 0, 0, 0.46)",
    overflow: "hidden",
  },
  header: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    rowGap: "16px",
    columnGap: "16px",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: "#2b2f29",
    padding: { default: "20px", [mobile]: "18px 16px" },
  },
  eyebrow: {
    display: "block",
    marginBottom: "5px",
    color: "#73786e",
    fontSize: "9px",
    fontWeight: 900,
    letterSpacing: "0.17em",
  },
  title: {
    display: "block",
    color: "#f0f2eb",
    fontSize: "22px",
    letterSpacing: "-0.025em",
  },
  description: {
    display: "block",
    marginTop: "4px",
    color: "#757b71",
    fontSize: "10px",
  },
  close: {
    display: "grid",
    width: "32px",
    height: "32px",
    placeItems: "center",
    borderWidth: 0,
    borderRadius: "8px",
    backgroundColor: { default: "transparent", ":hover": "#292d27" },
    color: "#92978e",
    font: "inherit",
    fontSize: "21px",
    cursor: "pointer",
  },
  controls: {
    display: "grid",
    rowGap: "10px",
    columnGap: "10px",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: "#2b2f29",
    padding: { default: "14px 20px", [mobile]: "13px 16px" },
  },
  search: {
    width: "100%",
    height: "38px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "#373c34",
    borderRadius: "9px",
    paddingInline: "11px",
    backgroundColor: "#0e110e",
    color: "#e8ebe4",
    font: "inherit",
    fontSize: "11px",
    outlineColor: "#dfff45",
  },
  filterRow: {
    display: "flex",
    flexDirection: { default: "row", [mobile]: "column" },
    alignItems: { default: "center", [mobile]: "stretch" },
    justifyContent: "space-between",
    rowGap: "8px",
    columnGap: "8px",
  },
  chips: {
    display: "flex",
    width: "100%",
    rowGap: "5px",
    columnGap: "5px",
    overflowX: "auto",
    scrollbarWidth: "none",
  },
  chip: {
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "#343930",
    borderRadius: "9px",
    paddingBlock: "6px",
    paddingInline: "8px",
    backgroundColor: "transparent",
    color: "#7e847a",
    font: "inherit",
    fontSize: "9px",
    fontWeight: 800,
    whiteSpace: "nowrap",
    cursor: "pointer",
  },
  chipActive: { borderColor: "#596149", backgroundColor: "#293026", color: "#e8ecdf" },
  range: {
    width: { default: "auto", [mobile]: "100%" },
    height: "30px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "#343930",
    borderRadius: "9px",
    paddingInline: "8px",
    backgroundColor: "#10130f",
    color: "#aeb4a9",
    font: "inherit",
    fontSize: "9px",
  },
  list: {
    flexGrow: 1,
    overflowY: "auto",
    padding: { default: "16px 20px 22px", [mobile]: "14px 16px 90px" },
    scrollbarColor: "#4a5046 transparent",
    scrollbarWidth: "thin",
  },
  countLabel: {
    display: "block",
    marginBottom: "8px",
    color: "#6e746a",
    fontSize: "9px",
    fontWeight: 900,
    letterSpacing: "0.15em",
  },
  event: {
    display: "grid",
    gridTemplateColumns: "28px minmax(0, 1fr) auto",
    rowGap: "10px",
    columnGap: "10px",
    marginBottom: "8px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "#2a2e28",
    borderRadius: "12px",
    padding: "12px",
    backgroundColor: "#171a15",
  },
  glyph: {
    display: "grid",
    width: "24px",
    height: "24px",
    placeItems: "center",
    borderRadius: "8px",
    backgroundColor: "#2a2f27",
    color: "#c9d0c0",
    fontSize: "10px",
    fontWeight: 900,
  },
  glyphDelivery: { backgroundColor: "#3a221c", color: "#f0b0a0" },
  glyphNotification: { backgroundColor: "#2f3320", color: "#dfff45" },
  glyphTimer: { backgroundColor: "#322f1c", color: "#e1c877" },
  glyphAttachment: { backgroundColor: "#243028", color: "#9fc4b0" },
  eventTitle: {
    display: "block",
    color: "#eef1ea",
    fontSize: "12px",
    fontWeight: 800,
  },
  eventDetail: {
    display: "block",
    marginTop: "3px",
    color: "#9aa194",
    fontSize: "11px",
    lineHeight: 1.4,
  },
  eventMeta: {
    display: "flex",
    flexWrap: "wrap",
    rowGap: "6px",
    columnGap: "6px",
    marginTop: "6px",
    color: "#6d7369",
    fontSize: "9px",
  },
  typeTag: {
    borderRadius: "999px",
    paddingBlock: "2px",
    paddingInline: "7px",
    backgroundColor: "#242821",
    color: "#b8bfb0",
    fontWeight: 800,
    textTransform: "uppercase",
    letterSpacing: "0.06em",
  },
  eventTime: { color: "#697066", fontSize: "9px", whiteSpace: "nowrap" },
  eventLink: { color: "inherit", textDecoration: "none" },
  empty: {
    marginTop: "24px",
    color: "#7a8076",
    fontSize: "12px",
    lineHeight: 1.45,
  },
  error: {
    marginTop: "16px",
    color: "#f0a090",
    fontSize: "12px",
  },
  note: {
    display: "block",
    marginTop: "14px",
    color: "#5f655c",
    fontSize: "9px",
    lineHeight: 1.4,
  },
});
